# Lecture Notes

## Lecture 1: 9/6 {-}

Goals for the first few lectures:

1. Develop basic understanding of floating point numbers (*fp* numbers)
2. Develop some basic notions of errors and their consequences

References:

i. David Goldberg (1991)
ii. John D. Cook (2009)
iii. Hingham (2002)

## Positional numeral system

We assume we have a decimal representation of numbers. I.e. that it exists. It is not within the scope of this class to prove this.

Now, this is NOT the optimal way for a computer to represent numbers. For various reasons, there are more desirable ways to store numbers. So we need a different way of representing the numbers.

Ingredients for different representation:

i. A base, refered to as $\beta$. It holds that $\beta \in {2,3,4,...}$
ii. A significand: a sequence of digits: $d_0.d_1d_2d_3d_4...$, where $d_j \in \{0, 1,...,\beta-1\}$
iii. An exponent: $e \in \mathbb{Z}$.

The representation $d_0.d_1d_2... \times \beta^e$ means $\left(d_0 + d_1\cdot \beta^{-1} + ... + d_{p-1}\beta^{-(p-1)}\right)\cdot \beta^e$.

### Floating Point Format

```{definition}
A fp is one that can be represented in a base $\beta$ with a fixed digit $p$ (precision), and whose exponent is between $e_{min}$ and $e_{max}$.
```


```{example}
Let $\beta = 10, p = 3, e_{min} = -1, e_{max} = 1$. Want to represent $0.1$. Several options:

i. Let d_0=0, d_1 = 0, d_2 = 1, e = 1.
ii. Let d_0=0, d_1 = 1, d_2 = 0, e = 0.
iii. d_0 = 1, d_1 = 0, d_2 = 0, e = -1.

If we fill into the equation above, we get 0.1:

\begin{align*}
  i:  & \left(0 + 0\cdot 10^{-1} + 1\cdot 10^{-2}\right)\cdot 10^{1} \\
  ii: & \left(0 + 1\cdot 10^{-1} + 1\cdot 10^{-2}\right)\cdot 10^{0} \\
  iii:& \left(1 + 0\cdot 10^{-1} + 1\cdot 10^{-2}\right)\cdot 10^{-1}
\end{align*}
```


```{definition}
A fp number is said to be *normalized* if $d_0 \neq 0$.
```

```{exercise}
What is the total number of values that can be represented in the normalized fp format with base $\beta, p, e_{min}, e_{max}$?

We count the different values each of the elements of a *fp* can take:

* $d_0$ can be from 1 to $\beta-1$, so $\beta-1$ different values.
* $d_1,...,d_{p-1}$ each takes a value in $\{0,1,...,\beta-1\}$. Hence, we can choose the digits $d_1,...,d_{p-1}$ in $\beta^{p-1}$ different ways.
* $e$ can take $e_{max} - e_{min} + 1$ different values (all integers from $e_{min}$ to $e_{max}$, both included, hence the $+1$).

So, in total, there are $(\beta-1)\cdot \beta^{p-1}\cdot (e_{max} - e_{min} + 1)$ different values that can be represented in the normalized fp format with base $\beta$, precision $p$, and $e_{min}, e_{max}$ given.
```


### IEEE Standards

IEEE have standards for how to deal with approximations and errors.

For our purposes, a bit is a single unit of storage on a computer, which can either be 0 or 1. Hence, we'll be focusing on fp formats where $\beta = 2$.

#### The 16 bit standard (half precision standard).

The 16 bits of storage are used in the following way, when following the 16 bit standard:

* 1 bit for the sign
    * 0 = positive
    * 1 = negative
* 5 bits for the exponent
    * 00000 is reserved for 0
    * 11111 is reserved for $\infty$
    * 30 exponents left: $2^5 - 2 = 30$
    * the 16 bit standard dictates that the used exponents are $-14,...,15$.
        * **Note**: $0$ is also included in this list of 30 exponents. This is because the $00000$ representation is reserved for integers, while $01111$ is used with non-integers.
* 11 bit for the significand.
    * 10 are actually stored -- we always work with normalized FP numbers, i.e. $\beta_0 = 1$.



**Question:** What are smallest and largest positive numbers that can be represented?

**Answer:** Smallest non-normalized number would be the one with the smallest possible exponent, and all digits of the significand are 0 except the very last one. So, the smallest non-normalized FP number in the 16 bit standard would be

$$
\left(0 + 0\cdot 2^{-1} + ... + 0\cdot 2^{-9} + 1\cdot 2^{-10}\right)\cdot 2^{-14} = 2^{-24} \approx 5.96\cdot 10^{-8}
$$

The smallest normalized number is the one with all digits $0$ (except for the leading digit, of course, which has to be $1$ for it to be normalized), and $e = -14$. So the smallest normalized FP number:

$$
\left(1 + 0\cdot 2^{-1} + ... + 0\cdot 2^{-10}\right)\cdot 2^{-14} = 2^{-14} \approx 6.10\cdot 10^{-5}
$$
Finally, the largest (finite) FP number in the 16 bit standard is the one where the exponent is as large as possible ($e = 15$), and all digits are $1$. So

$$
\left(1 + 1\cdot 2^{-1} + ... + 1\cdot 2^{-10}\right)\cdot 2^{15} = 65504
$$



#### Lecture 2: 9/11 {-}

#### The 32 bit standard (single precision)

The 32 bits of storage are used in the following way, when following the 32 bit standard:

* 1 bit for the sign
    * 0 = positive
    * 1 = negative
* 8 bits for the exponent
    * 00000000 is reserved for 0
    * 11111111 is reserved for $\infty$
    * exponents left: $2^8 - 2 = 254$
    * the 32 bit standard dictates that the used exponents are $-126,...,127$.
        * **Note**: $0$ is also included in this list of the 254 exponents. This is because the $00000000$ representation is reserved for integers, while $01111111$ (I think this is the representation for $0$ here...) is used with non-integers.
* 24 bit for the significand.
    * 23 are actually stored -- we always work with normalized FP numbers, i.e. $\beta_0 = 1$.



**Question:** What are smallest and largest positive numbers that can be represented in the 32 bit standard?

**Answer:** Smallest non-normalized number would be the one with the smallest possible exponent, and all digits of the significand are 0 except the very last one. So, the smallest non-normalized FP number in the 32 bit standard would be

$$
\left(0 + 0\cdot 2^{-1} + ... + 0\cdot 2^{-22} + 1\cdot 2^{-23}\right)\cdot 2^{-126} = 2^{-149} \approx 1.40\cdot 10^{-45}
$$

The smallest normalized number is the one with all digits $0$ (except for the leading digit, of course, which has to be $1$ for it to be normalized), and $e = -126$. So the smallest normalized FP number:

$$
\left(1 + 0\cdot 2^{-1} + ... + 0\cdot 2^{-23}\right)\cdot 2^{-126} = 2^{-126} \approx 1.18\cdot 10^{-38}
$$
Finally, the largest (finite) FP number in the 32 bit standard is the one where the exponent is as large as possible ($e = 127$), and all digits are $1$. So

$$
\left(1 + 1\cdot 2^{-1} + ... + 1\cdot 2^{-126}\right)\cdot 2^{127} = 3.40\cdot 10^{38}
$$



#### The 64 bit standard (double precision)

The 64 bits of storage are used in the following way, when following the 64 bit standard:

* 1 bit for the sign
    * 0 = positive
    * 1 = negative
* 11 bits for the exponent
    * 00000000 is reserved for 0
    * 11111111 is reserved for $\infty$
    * exponents left: $2^11 - 2 = 2046$
    * the 64 bit standard dictates that the used exponents are $-1024,...,1023$.
        * **Note**: $0$ is also included in this list of the 254 exponents. This is because the $00000000$ representation is reserved for integers, while $01111111$ (I think this is the representation for $0$ here...) is used with non-integers.
* 53 bit for the significand.
    * 52 are actually stored -- we always work with normalized FP numbers, i.e. $\beta_0 = 1$.

### Errors

#### Units in the Last Place (ULP)

#### Absolute and Relative Error

Let $fl: \mathbb{R}_{\geq 0} \rightarrow \mathcal{S}$ be a function that takes a real value and return a FP number. Then we define the absolute and relative error as follows:



```{definition}
Let $z \in \mathbb{R}_{\geq 0}$. The *absolute error* is defined as

$$
\left | fl(z) - z \right | .
$$

The *relative error* is defined as

$$
\left | \frac{fl(z)-z}{z} \right |
$$
```

```{lemma, label = "absolute-error-bound"}
If $z$ has exponent $e$, then the maximum absolute error is $\frac{\beta^{e-p+1}}{2}$.
```

```{proof}

```

```{lemma}
If $z$ has exponent $e$, then the maximum relative error is $\frac{\beta^{1-p}}{2}$.
```

```{proof}
If $z$ has exponent $e$, then $\beta^{e}\leq z$. Using this with \@ref(lem:absolute-error-bound), we get that


$$
\left | \frac{fl(z)-z}{z} \right | \leq \frac{\beta^{e-p+1}}{2\beta^e} = \frac{\beta^{1-p}}{2}.
$$
```


**Note:** the upper bound of the relative error is called the *machine epsilon*. This can be obtained in Julia using the function `eps`.

#### The Fundamental Axiom

... is that for any of the four arithmetic operations ($+, -, \cdot, /$), we have the following error bound:

$$
fl(x \text{op} y) = (x \text{op} y)(1+\delta),
$$

with $|\delta| \leq u$, where $u$ is commonly $2\cdot \epsilon$. (**NOTE: NEED TO CLARIFY IF THE ABOVE IS CORRECT!**)



**Example:** Matrix storage. Let $A \in \mathbb{R}^{m\times n}$. Then:

$$
\left| fl(A) - A \right | \leq u \left | A \right |
$$



**Example:** Dot product. Let $x,y \in \mathbb{R}^{n}$. Recall that the dot product of $x$ and $y$ is definted as $x'y = \sum_{i=1}^{n} x_i \cdot y_i$. This can be calculated in the following way:

```{julia results='hide'}
fl = function(x,y)
  # Get length of x
  n = length(x)
  # Check that length of y is equal to length of x. If not, throw error.
  if(length(y) != n)
    return "ERROR: y does not have same dimension as x"
  end

  # s will be the result of the dot product calculation
  s = 0

  for i = 1:n
    s += x[i]*y[i]
  end

  return(s)

end
```



Next we want to prove the following lemma:

```{lemma}
Let $x,y \in \mathbb{R}^n$, and $n\cdot u \leq 0.01$. Then

$$
\left | fl(x'y) - x'y \right | \leq 1.01 \cdot n\cdot u \cdot \left|x\right|'\left|y\right|
$$
```

#### Lecture 3: 9/13 {-}

To prove the lemma above, we will need another lemma...

```{lemma, lemForProof}
If $|\delta_i| \leq u, \forall i=1,\ldots,n$ s.t. $n\cdot u < 2$. Let $1 + \eta = \prod_{i=1}^{n}(1 + \delta_i)$. Then

$$
|\eta | \leq \frac{n\cdot u}{1-\tfrac{n\cdot u}{2}}
$$
```

```{proof}
Using the definition of $\nu$, we can rewrite it to get

$$
| \eta | = \left | \prod_{i=1}^n (1 + \delta_i) - 1 \right |.
$$

By induction, we will show that the expression above is less than or equal to $(1 + u)^n - 1$. [TO BE COMPLETED!]

Since $1+u \leq e^{u}$ for all $u \in \R$, we have that

\begin{align*}
  | \eta | &\leq e^{n\cdot u} - 1 \\
          &\leq n\cdot u + \frac{(n\cdot u)^2}{2!} + \frac{(n\cdot u)^3}{3!} + \ldots \text{(used the Taylor expansion)}\\
          &\leq n\cdot u + \frac{(n\cdot u)^2}{2^1} + \frac{(n\cdot u)^3}{2^2} + \frac{(n\cdot u)^4}{2^3} + \ldots (\text{used that } x! > 2^{x-1} \text{ for } x > 1) \\
          &= \sum_{k=0}^{\infty} n\cdot u \left(\frac{n\cdot u}{2}\right)^k \text{\small (identify this as a geometric series with } r = \tfrac{n\cdot u}{2} \text{, \small which is less than 1 by assumption)} \\
          &= \frac{n\cdot u}{1-\tfrac{n\cdot u}{2}},
\end{align*}

which is exactly what we wanted.
```



With this in hand, we will prove the previously stated lemma.

```{proof}
Let $s_p$ denote the value of $s$ after the $p$'th iteration of the algorithm described above. Then, since we're assuming the Fundamental Axiom, we have that $s_1 = fl(x_1y_y) = x_1 y_1 (1 + \delta_1)$, where $|\delta_1| \leq u$. We can similarly find $s_p$ as

\begin{align*}
s_p &= fl(s_{p-1} + fl(x_p y_p)) \\
    &= (s_{p-1} + fl(x_p y_p))(1 + \epsilon_p) (\text{where } |\epsilon_p| \leq u) \\
    &= (s_{p-1} + x_py_p(1 + \delta_p))(1 + \epsilon_p) (\text{where } |\delta_p| \leq u).
\end{align*}

Let $\epsilon_1 = 0$. $s_p$ is a recursive formula, and can be rewritten as follows:

$$
s_p = \sum_{i=1}^p x_iy_i (1 + \delta_i)\prod_{j=1}^p (1 + \epsilon_j).
$$

So,

\begin{align*}
  | s_n - x^\prime y |  &= \left | \sum_{i=1}^n (x_i y_i)(1 + \delta_i)\prod_{j=1}^p (1 + \epsilon_j) - \sum_{i=1}^{n}x_iy_i\right | \\
                        &= \left | \sum_{i=1}^n (x_i y_i)\left((1 + \delta_i)\prod_{j=1}^p (1 + \epsilon_j) - 1 \right) \right | \\
                        &\leq \sum_{i=1}^n \left |x_i y_i \right |\left | (1 + \delta_i)\prod_{j=1}^p (1 + \epsilon_j) - 1 \right| .
\end{align*}

We now use \@ref(lem:lemForProof) to get:

\begin{align*}
\sum_{i=1}^n \left |x_i y_i \right |\left | (1 + \delta_i)\prod_{j=1}^p (1 + \epsilon_j) - 1 \right| &\leq  \frac{nu}{1-\tfrac{nu}{2}} \sum_{i=1}^n \left |x_i y_i \right | \\
&\leq \frac{nu}{0.995} \sum_{i=1}^n |x_i| |y_i | \\
&\leq 1.01 \cdot nu \cdot |x|^\prime |y|
\end{align*}

```

### Square Linear Systems

In the following, let $A \in \R^{n \times m}$ be an invertible matrix, and assume $Ax = b$ for a $b \neq 0$. This implies that $x = A^{-1}b$.

```{theorem, label = "kappa-bound"}
Let $\kappa_\infty = \norm{A}_\infty \norm{A^{-1}}_\infty$. Assume we can store $A$ with precision $E$ (i.e. as $A+E$), where $\norm{E}_\infty \leq u \norm{A}_\infty$, and $b$ with precision $e$ (i.e. as $b+e$), where $\norm{e}_\infty \leq u \norm{b}_\infty$.

If $\norm{A+E}\hat{x} = b+e$ and $u\cdot \kappa_\infty < 1$, then

$$
  \frac{\norm{x-\hat{x}}_\infty}{\norm{x}} \leq \frac{2\cdot u \cdot \kappa_\infty}{1-u\cdot \kappa_\infty}
$$
```

```{lemma, label = "proofHW"}
Let $I\in \R^{n \times n}$ be the identity matrix, and $F \in \R^{n\times n}$ s.t. $\norm{F}_p < 1$ for some $p \in [1,\infty]$. Then $I-F$ is invertible, and

$$
  \norm{(I-F)^{-1}}_p \leq \frac{1}{1-\norm{F}_p}
$$
```

```{proof}
**HOMEWORK**
```


```{lemma}
Suppose $\exists \epsilon > 0$ s.t. $\norm{\Delta A} \leq \epsilon \norm{A}$ and $\norm{\Delta b} \leq \epsilon \norm{b}$, and $y$ s.t. $(A+\Delta A)y = b+\Delta b$.

If $\epsilon \norm{A}\norm{A^{-1}} = r < 1$, then $A+\Delta A$ is invertible and $$\frac{\norm{y}}{\norm{x}} \leq \frac{1+r}{1-r}.$$
```

```{proof}
Note that $A+\Delta A = A\left (I + A^{-1}\Delta A\right ) = A\left (I - \left(- A^{-1}\Delta A\right)\right)$. Since $\norm{-A^{-1}\Delta A} = \norm{A^{-1}\Delta A} \leq \epsilon \norm{A^{-1}}\cdot \norm{A} < 1$ (by assumptions), Lemma \@ref(lem:proofHW) gives us that $I + A^{-1}\Delta A$ is invertible. Since $A$ is also invertible (again, by assumption), $A+\Delta A$ is invertible (product of two invertible matrices is invertible).

Performing some linear algebra:

\begin{align*}
  (A + \Delta A) &=  b + \Delta b \Leftrightarrow \\
  A(I + A^{-1} \Delta A) y &= b + \Delta b \Leftrightarrow \\
  (I + A^{-1} \Delta A) y &= A^{-1}b + A^{-1}\Delta b \Leftrightarrow \\
  y &= (I + A^{-1} \Delta A)^{-1} A^{-1}b + A^{-1}\Delta b.
\end{align*}

Remember that $A^{-1}b = x$. From the definition of $r$ we have that $\norm{A^{-1}} = \frac{r}{\norm{A}}$. These two identities with the assumption that $\norm{\Delta b} \leq \epsilon b$ gives us

$$
\begin{aligned}
  \norm{y} &\leq \norm{(I + A^{-1}\Delta A)^{-1}} \left( \norm{x} + \norm{A^{-1}\Delta b}\right) \\
  &\leq \frac{1}{1-\norm{A^{-1}\Delta A}} \left( \norm{x} + \frac{r}{\epsilon \norm{A}} \cdot \norm{\Delta b} \right) \\
  &\leq \frac{1}{1-r} \left( \norm{x} + \frac{r}{\epsilon \norm{A}} \cdot \epsilon \norm{b} \right) \\
  &= \frac{1}{1-r} \left( \norm{x} + \frac{r \cdot \norm{b}}{\norm{A}} \right).
\end{aligned}
$$

Finally, recall that $Ax=b$, hence $\norm{A}\cdot\norm{x} \geq \norm{b}$, so $\norm{x} \geq \frac{\norm{b}}{\norm{A}}$. So,

$$
\begin{aligned}
  \norm{y} \leq \frac{1}{1-r}  \left( \norm{x} + r \cdot \norm{x} \right) \Leftrightarrow \\
  \frac{\norm{y}}{\norm{x}} \leq \frac{1+r}{1-r}.
\end{aligned}
$$

```

```{lemma}
$$\frac{\norm{y - x}}{\norm{x}} \leq \frac{2\epsilon \norm{A^{-1}}\cdot \norm{A}}{1-r}.$$
```

```{proof}

$$
\begin{aligned}
  \left(A+\Delta A\right)y &= b + \Delta b \Leftrightarrow \\
  Ay - b &= \Delta b - \Delta Ay \Leftrightarrow \\
  y - A^{-1}b &= A^{-1} \Delta b - A^{-1}\Delta A y \Leftrightarrow \\
  y - x &= A^{-1} \Delta b - A^{-1}\Delta A y \Leftrightarrow \\
  \norm{y - x} &\leq \norm{A^{-1}} \norm{\Delta b} + \norm{A^{-1}} \norm{\Delta A}\norm{y} \\ %\Leftrightarrow \\
  &\leq \norm{A^{-1}} \epsilon \norm{b} + \norm{A^{-1}} \epsilon\norm{A}\norm{y} \\ %\Leftrightarrow \\
  &\leq \epsilon \norm{A^{-1}} \norm{A}\norm{x} + \epsilon\norm{A^{-1}}\norm{A}\norm{y} \\ % \Leftrightarrow \\
  &\leq \epsilon \norm{A^{-1}} \norm{A}\left(\norm{x} + \norm{y}\right) \\
  &= \epsilon \norm{A^{-1}} \norm{A}\left(\norm{x} + \frac{1+r}{1-r}\norm{x}\right) \Leftrightarrow \\
\frac{\norm{y-x}}{\norm{x}} &\leq \epsilon \norm{A^{-1}} \norm{A} \left(\frac{1-r}{1-r} + \frac{1+r}{1-r}\right) \\
  &= 2\epsilon \norm{A^{-1}} \norm{A} \frac{1}{1-r}
\end{aligned}
$$

```

## Orthogonalization

Goals

1) Introduce and prove the existence of QR decomposition
2) Overview of the algorithm to perfor QR decomposition
3) Solve least squares problems
4) "Large" data problems

Outline

1) Motivating problems and solutions with QR
2) Gram-Schmidt procedure, existence of QR
3) Householder, Givens
4) "Large" least squares problems datadown

### Motivating problems

```{example, name = 'Motivating Problem 1 (Consistent Linear System)', label = "linear-system"}
Assume $A \in \R^{n\times m}, n \geq m, \text{rank}(A) = m$, and $b \in \text{range}(A) \subset R^m$. Find $x \in \R^m$ s.t. $Ax = b$.
```


```{example, name = 'Motivating Problem 2 (Least Squares Regression)', label = "least-squares"}
Assume $A \in \R^{n\times m}, n \geq m, \text{rank}(A) = m$, and $b \in R^n$. Find $x \in \R^m$ s.t. $$x \in \argmin_{y \in \R^m} \norm{Ay-b}_2.$$
```


```{example, name = 'Motivating Problem 3 (Underdetermined Linear System', label = "und-linear-system"}
Assume $A \in \R^{n\times m}, n \geq m, \text{rank}(A) < m$, and $b \in \text{range}(A)$. Find $x \in \R^m$ s.t.

$$x \in \argmin_{y \in \R^m} \left\{ \norm{y}_2 \left | Ay = b \right\} \right . .$$
```

```{example, name = 'Motivating Problem 4 (Underdetermined Least Squares Regression)', label = "und-least-squares"}
Assume $A \in \R^{n\times m}, n \geq m, \text{rank}(A) < m$, and $b \in \R^n$. Find $x \in \R^m$ s.t.

$$x \in \argmin_{z \in \R^m} \left\{ \norm{z}_2 \left | \norm{Ay - b}_2 = \min_{y \in \R^m} \norm{Ay-b}_2 \right\} \right . .$$
```

```{example, name = 'Motivating Problem 5 (Constrained Least Squares Regression)', label = "constrained-least-squares"}
Assume $A \in \R^{n\times m}, n \geq m, \text{rank}(A) = m$, and $b \in \R^n$. Let $C \in \R^{p\times m}, \text{rank}(C) = p$, and $d \in \R^{p}$. Find $x \in \R^m$ s.t.

$$x = \argmin_{y \in \R^m} \norm{Ay - b}_2\quad \text{s.t.} \quad Cy = d.$$
```

Before we take a crack at solving these problems, we will need to get some definitions down.

```{definition, name = "Permutation Matrix", label = "perm-matrix"}
A permutation matrix is a square matrix such that each column has exactly one element that is $1$, the rest are $0$.
```

```{example}
The following is a permutation matrix:

$$
  \begin{bmatrix}
    0 & 1 \\
    1 & 0
  \end{bmatrix}
$$

```

```{definition, name = "Orthogonal Matrix", label = "orthogonal"}
A matrix $Q$ is said to be an *orthogonal matrix* if $Q^T Q = Q Q^T = I$.
```

Note: for an orthogonal matrix $Q \in \R^{n\times m}$, it holds that $\norm{Q_{i*}}_2 = 1$ for all $i=1,\ldots,n$, and $\norm{Q_{*j}}_2 = 1$ for all $j = 1,\ldots, m$.^[Here we use the notion $Q_{i*}$ to mean the $i$'th row, and $Q_{*j}$ to mean the $j$'th column of $Q$.]

```{definition, name = "Upper Triangular Matrix"}
A matrix $R$ is an *upper triangular matrix* if $R_{ij} = 0$ for all $i>j$.
```

### Lecture 4: 9/18 {-}

### QR Decomposition

In order to actually solve the problems listed above, we need the QR Decomposition:

```{theorem, name = "Existence of QR Decomposition", label = qr-decomposition}
Let $A \in \R^{n \times m}$ and let $r = rank(A)$. Then there exists:

1) an $m\times m$ permutation matrix $\Pi$,
2) an $n \times n$ orthogonal matrix $Q$,
3) an $r \times r$ upper triangular matrix $R$, with non-zero diagonal elements (i.e. invertible)
4) an $r \times (m-r)$ matrix S (if $m > r$),

such that

$$
  A = Q \begin{bmatrix} R & S \\ 0 & 0 \end{bmatrix} \Pi^T.
$$

```




With this in hand, we can solve the motivating problems stated above.

```{solution, name = "Example \\@ref(exm:linear-system)"}

We want to find $x$ such that $Ax = b$.

We use theorem \@ref(thm:qr-decomposition) to rewrite this as $Q \begin{bmatrix} R \\ 0 \end{bmatrix} \Pi^T x = b$. Note that since $\text{rank}(A) = m$, there is no $S$ matrix.

Now, since $Q$ is an orthogonal matrix, we know that $Q^{-1} = Q^T$, so

\begin{equation}
  \begin{bmatrix} R \\ 0 \end{bmatrix} \Pi^T x = Q^T b = c = \begin{bmatrix} c_1 \\ 0 \end{bmatrix}. (\#eq:sol-linear-system)
\end{equation}

So now the equation we are trying to solve becomes

$$
  R \Pi^T x = c_1.
$$

Since $R$ is an upper triangular matrix with non-zero diagonal elements, it is invertible. Since $\Pi$ is a permutation matrix, $\Pi^{-1} = \Pi^T$. Using this we can find the solution:

$$
  x = \Pi R^{-1} c_1.
$$

```

```{solution, name = "Example \\@ref(exm:least-squares)"}
We want to find $x$ such that $x \in \argmin_{y \in \R^m}\norm{Ay-b}_2$.

Once again, $\text{rank}(A) = m$, so using theorem \@ref(thm:qr-decomposition), we can rewrite the expression we are trying to minimize as

$$
  \min \norm{Q \begin{bmatrix} R \\ 0 \end{bmatrix}\Pi^T y - b}_2. (\#eq:least-squares-eq1)
$$

Since $Q^T = Q^{-1}$ is orthogonal, $\norm{Q^T x}_2 = \norm{x}_2$ for all $x$ (homework exercise \@ref(exr:q402)). So, we get that \@ref(eq:least-squares-eq1) is the same as

$$
  \min\norm{\begin{bmatrix} R \\ 0 \end{bmatrix} \Pi^T y - Q^T b}_2.
$$

Now let $c = Q^T b$. Then, $c$ is of the form $\begin{bmatrix} c_1 \\ c_2 \end{bmatrix}$, where $c_2$ is the last $n-r$ rows (i.e. corresponding to the $0$ rows of $\begin{bmatrix} R \\ 0 \end{bmatrix}$). Then

$$
  \min\norm{\begin{bmatrix} R \Pi^T y - c_1 \\ -c_2 \end{bmatrix}}_2 = \min \sqrt{\norm{R \Pi^T y - c_1}_2^2 + \norm{c_2}_2^2}.
$$

Now this is minimized by $\argmin_y \norm{R \Pi^T y - c_1}_2^2$. As before, $R^{-1}$ exists since $R$ is upper triangular with non-zero diagonal elements, $\Pi^T = \Pi^{-1}$ since $\Pi$ is a permutation matrix, so

$$
  \begin{aligned}
    x &= \argmin_y \norm{R \Pi^T y - c_1}_2^2 \Leftrightarrow \\
    R \Pi^T x &= c_1 \Leftrightarrow \\
    x &= \Pi R^{-1} c_1.
  \end{aligned}
$$

```

```{solution, name = "Example \\@ref(exm:und-linear-system)"}

In this scenario, $\text{rank}(A) = r < m$. We are looking for $x \in \argmin_{y}\left\{\norm{y}_2 \left | Ay = b\right\}\right .$. Using theorem \@ref(thm:qr-decomposition), we can rewrite this as $\argmin_y\left\{\norm{y}_2 | Q\begin{bmatrix} R & S \\ 0 & 0 \end{bmatrix} y = b \right\}$, and multiplying by $Q^T$, $\argmin_y\left\{\norm{y}_2 \left | \begin{bmatrix} R & S \\ 0 & 0 \end{bmatrix} y = Q^T b \right\} \right .$. We introduce the vector $c$ such that $Q^T b = \begin{bmatrix} c & 0 \end{bmatrix}^T$ ($0$ entries correspond to $0$ rows in $\begin{bmatrix} R & S \\ 0 & 0 \end{bmatrix}$). If we furthermore write $\Pi^T y$ as $\begin{bmatrix} z_1 & z_2 \end{bmatrix}^T$.

Then, since $\norm{y}_2 = \norm{z}_2$, our problem becomes

$$
  \begin{aligned}
    x &\in \argmin_z \left\{\norm{z}_2 \left | R z_1 + S z_2 = c \right\}\right. \\
    x &\in \argmin_z \left\{\norm{z}_2 \left | z_1 = R^{-1} c - R^{-1} S z_2 \right\}\right. \\
    x &\in \argmin_z \sqrt{\norm{R^{-1}c - R^{-1} S z_2}_2^2 + \norm{z_2}_2^2} \\
    x &\in \argmin_z \left\{\norm{R^{-1}c - R^{-1} S z_2}_2^2 + \norm{z_2}_2^2\right\},
  \end{aligned}
$$

where the last equality is a consequence of the result proved in homework \@ref(exr:q403). Now, let $d = R^{-1}c$ and $P = R^{-1}S$. Then we can find the minimum of the above expression by differentiating and setting equal to zero:


\begin{align}
  0 &= -P^Td + (P^TP + I)z_2 \rightarrow \\
  z_2 &= (P^T P + I)^{-1}P^Td.
\end{align}

```

```{solution, name = "Example \\@ref(exm:und-least-squares)"}

We want to find $\min_z \left\{ \norm{z}_2 \left \vert z \in \argmin_y \norm{Ay - b}_2\right\} \right .$ Use theorem \@ref(thm:qr-decomposition):

$$\begin{aligned}
  \min_z \left\{ \norm{z}_2 \left \vert z \in \argmin_y \norm{Ay - b}_2\right\} \right . &= \left\{ \norm{z}_2 \left \vert z \in \argmin_y \norm{\begin{bmatrix} R & S \\ 0 & 0 \end{bmatrix} \Pi^T y - Q^T b}_2\right\} \right . \\
  &= \left\{ \norm{w}_2 \left \vert w \in \argmin_y \norm{\begin{bmatrix} R & S \\ 0 & 0 \end{bmatrix}  y - Q^T b}_2\right\} \right .,
\end{aligned}$$

since $\norm{y}_2 = \norm{\Pi^T y}_2$. This is exactly the problem solved in example \@ref(exm:und-linear-system). In conclusion,

$$
  w = \begin{bmatrix} R^{-1}(c_1 - Sy_y) \\ y_2 \end{bmatrix}.
$$

```


```{solution, name = "Example \\@ref(exm:constrained-least-squares)"}

```


### Existence of QR-decomposition.

To prove the existence of the QR-decomposition, we need the Gram-Schmidt process.

```{lemma, name = "The Gram-Schmidt Process", label = "gsp"}
Let $r \in \N$. Given a set of linearly independent vectors $\{a_1, \ldots, a_r\}$, there exists a set of orthonormal vectors $\{q_1, \ldots, q_r\}$ such that $\text{span} \{q_1, \ldots, q_r\} = \text{span}\{a_1, \ldots, a_r\}$.

The $q_i$'s are given by...

```

```{proof}
We will prove this by induction. For $i=1$: let $R_{11} = \norm{a_1}_2$, $q_1 = \frac{1}{R_11}a_1$. Notice that $\norm{q_1} = 1$.

(At this point, it might be beneficial to check out the intuitive side note (\@ref(cnj:gram-schmidt-remark)))

Define $q^r$ in the following way: let $R_{ir} = q_i^\prime a_r$, $\tilde{q}_r = a_r - \sum_{i=1}^{r-1} R_{ir}q_i$, and $R_{rr} = \norm{\tilde{q}_r}_2$. Then $q_r = \frac{\tilde{q}_r}{R_{rr}}$. (Note: $\tilde{q}_r \neq 0$ since the $a_i$s are linearly independent, and $q_i$ is given as a linear combination of $a_1, \ldots, a_i$.)

Assume the result holds for $i \le r-1$. I.e. we have vectors $q_1, \ldots, q_{r-1}$ given as above, and that

i) $\text{span}\{q_1, \ldots, q_{r-1}\} = \text{span}\{a_1, \ldots, a_{r-1}\}$,
ii) $q_i \cdot q_j$ for all $i,j = 1, \ldots, r-1$ with $i \neq j$,
iii) $q_i^\prime \cdot q_i = 1$ for all $i = 1, \ldots, r-1$.

Now, we want to show that we can construct a $q_r$ such that

a) $\text{span}\{q_1, \ldots, q_r\} = \text{span}\{a_1, \ldots, a_r\}$,
b) $q_r \cdot q_j = 0$ for all $j = 1, \ldots, r-1$,
c) $q_r^\prime \cdot q_r = 1$.

We start from below.

c) By definition of $q_r$: $q_r^\prime q_r = \frac{\tilde{q}_r^\prime \tilde{q}_r}{R_{rr}^2} = \frac{\norm{\tilde{q}_r}^2}{R_{rr}^2} = 1$.
b) Let $i < r$. Then

$$\begin{aligned}
  q_i^{\prime} \tilde{q}_r &= q_i^\prime a_r - \sum_{j=1}^{r-1} R_{jr} q_i^\prime q_j \\
                           &= q_i^\prime a_r - R_{ir} q_i^\prime q_i \\
                           &= q_i^\prime a_r - R_{ir} = 0 \text{ (by definition of } R_{ir}\text{)}.
\end{aligned}$$

a) We need to show that $a_r$ can be written as a linear combination of $q_i$s.

$$\begin{aligned}
  \sum_{i=1}^r R_{ir} q_i &= \sum_{i=1}^{r-1} R_{ir} q_i + R_{rr} q_r \\
                          &= \sum_{i=1}^{r-1} R_{ir} q_i + R_{rr} \frac{1}{R_{rr}} \tilde{q}_r \\
                          &= \sum_{i=1}^{r-1} R_{ir} q_i + R_{rr} \frac{1}{R_{rr}} \left(a_r - \sum_{i=1}^{r-1} R_{ir}q_i \right) \\
                          &= \sum_{i=1}^{r-1} R_{ir} q_i + a_r - \sum_{i=1}^{r-1} R_{ir}q_i \\
                          &= a_r.
\end{aligned}$$

```

```{conjecture, name = "Intuitive side note", label = "gram-schmidt-remark"}
It is fairly easy to find $q_2$. We want to find it such that $a_2 = R_{12}q_1 + R_{22} q_2$, and $\norm{q_2}_2 = 1$ and $q_1 \perp q_2$, i.e. $q_1 \cdot q_2 = 0$. So, if we multiply the equation by $q_1$, we get that $q_1 a_2 = R_{12}$. Substituting this into the first equation, $q_2 = \frac{a_2 - R_{12} q_1}{R_{22}}$.

Note that this is a circular argument, and hence not a formal way of doing this.
```

### Lecture 5: 9/20 {-}

(Finished up proof of The Gram-Schmidt Process (\@ref(lem:gsp)))


```{conjecture, name = "Gram-Schmidt in Matrix Form"}
If we write up $a_1, \ldots, a_r$ in a matrix, we see that

$$
  \begin{bmatrix}
    a_1 & \dots & a_r
  \end{bmatrix} =
      \begin{bmatrix}
        q_1 & \dots & q_r
      \end{bmatrix}
        \begin{bmatrix}
          R_{11} & R_{12} & \dots & R_{1r} \\
          0      & R_{22} & \dots & R_{2r} \\
          \vdots & \ddots & \ddots &  \vdots \\
          0 & \ldots & 0 & R_{rr}
        \end{bmatrix}
$$

This is quite similar to the result we are after (the QR-decomposition \@ref(thm:qr-decomposition)).
```

```{proof, name = "Proof of theorem \\@ref(thm:qr-decomposition)"}
Since $\text{rank}(A) = r$, $A$ has $r$ linearly independent columns. Hence, there exists a permutation matrix $\Pi$ such that

$$
  A \Pi = \begin{bmatrix} a_1 & \dots & a_r & a_{r+1} \dots a_m \end{bmatrix},
$$

where $a_1, \ldots, a_r$ are linearly independent, and $a_{r+1}, \ldots, a_m$ are linearly dependent on the first $r$ columns.

Using Gram-Schmidt (lemma \@ref(lem:gsp)), we know that there exists $\tilde{Q} \in \R^{n \times r}, R \in \R^{r \times r}$ such that $A\Pi = \tilde{Q} R$. Since $\text{span}\{\tilde{q}_1, \ldots, \tilde{q}_r\}$ (columns of $\tilde{Q}$) is equal to $\text{span}\{a_1, \ldots, a_r\}$, there exists an $s_{k(j-r+2)}$ for any $j \in \{r+1, \ldots, m\}$ and $k \in \{1, \ldots, r\}$ such that $a_j = \sum_{k=1}^r s_{k(j-r+2)}q_k$. So,

$$
  A\Pi = \tilde{Q} \begin{bmatrix} R & S \end{bmatrix}.
$$

This is almost the form we want, BUT $\tilde{Q}$ is not orthonormal (it is not square). However, we know that we can pick $n-r$ vectors from $\R^n$ such that adding these as columns to $\tilde{Q}$ we get a set of $n$ linearly independent columns. Now, use Gram-Schmidt to normalize. Since the first $r$ columns are already normalized, these will stay the same. The result is a matrix $Q$, where the columns are all length $1$, and they are all linearly independent. I.e. $Q^TQ = I$. So, $A\Pi = Q \begin{bmatrix} R & S \\ 0 & 0 \end{bmatrix}$, hence

$$
  A = Q \begin{bmatrix} R & S \\ 0 & 0 \end{bmatrix} \Pi^T.
$$

```


Basically, this gives us a way to perform QR decomposition. However, using the Gram-Schmidt procedure is NOT numerical stable. I.e. we might end up with matrices $Q, R$, and $S$ from which we CANNOT recover $A$. To overcome this, there is a different method called the *Modified Gram-Schmidt Procedure*.

```{lemma, name = "The Modified Gram-Schmidt Procedure", label = 'mod-gsp'}
**HOMEWORK**
```

```{definition, name = 'Householder Reflections', label = 'householder'}
A matrix $H = I - 2vv^\prime$, where $\norm{v}_2 = 1$, is called a *Householder Reflection*.
```

A Householder reflection takes any vector and reflects it over $\{tv: t \in \R\}$.

```{lemma}
Householder reflections are orthogonal matrices.
```

```{proof}
By definition of a Householder matrix (\@ref(def:householder)), $H = I - 2vv^\prime$ for a $v$ with $\norm{v}_2 = 1$.

So,

$$\begin{aligned}
  H^\prime H &= (I - 2vv^\prime)^\prime (I - 2vv^\prime) \\
             &= (I^\prime - 2(vv^\prime)^\prime)(I - 2 vv^\prime)\\
             &= (I - 2vv^\prime)(I - 2 vv^\prime) \\
             &= I - 2vv^\prime - 2vv^\prime + 4 vv^\prime v v^\prime \quad\left(\text{ recall: } v^\prime v = \norm{v}_2 = 1\right)\\
             &= I - 2vv^\prime - 2vv^\prime + 4 vv^\prime \\
             &= I.
\end{aligned}$$  
    
So by definition (\@ref(def:orthogonal)), $H$ is an orthogonal matrix.
```

```{lemma}
There exists Householder refelctions $H_1, \cdots, H_r$ such that $H_r \cdots H_1 \cdot A\cdot\Pi = R$.
```

```{proof}
Let $A\Pi = \begin{bmatrix} a_1 & \cdots & a_r \end{bmatrix}$. Choose $H_1$ s.t. $H_1 a_1 = R_{11} e_1 = a_1 - 2v_1v_1^\prime a_1$ (last equality due to definition of Householder reflections). This is equivalent to $v_1(2v_1^\prime a_1) = a_1 - R_{11}e_1$.

Now, let $v_1 = \frac{a_1 - R_{11}e_1}{\norm{a_1 - R_{11}e_2}_2}$. Plug this into the equation for $R_{11}e_1$ above to get

$$
  R_{11}e_1 = a_1 - \frac{(a_1 - R_{11}e_1)}{\norm{a_1 - R_{11}e_1}_2}\frac{a_1^\prime a_1 - R_{11} a_1^\prime e_1}{\norm{a_1 - R_{11}e_1}_2}.
$$

If we multiply this by $e_1^\prime$ from the right, we get

$$
  R_{11} = \pm \norm{a_1}_2, v_1 = \frac{a_1 - \norm{a_1}e_1}{\norm{a_1 - \norm{a_1}_2 e_1}_2}.
$$

$$
  H_1 = I - \frac{a_1 - \norm{a_1}_2e_1)((a_1 - \norm{a_1}_2 e_1)}{\norm{a_1 - \norm{a_1}_2 e_1}_2^2}
$$

```


```{definition, name = "Givens Rotations", label = "givens"}
A *Givens Rotation* is a matrix $G^{(i,j)}$ with entries $(g_{ij})$ such that

i) $g_{ii} = g_{jj} = \lambda$ (the $i$th and $j$th elements of the diagonal are $\lambda$).
ii) $g_{kk} = 1$ for all $k \notin \{i,j\}$. (all other diagonal elements are $1$)
iii) $g_{ij} = -g_{ji} = \sigma$
iv) $g_{ij} = 0$ for all other pairs of $i,j$.

In words: $G^{(i,j)}$ is the identity matrix with the $i$th and $j$th diagonal elements made $\lambda$, and the entries at $(i,j)$ and $(j,i)$ are $\sigma$.

```

```{example, name = "2x2 Givens rotation to create upper triangular matrix."}
The general $G^{(1,2)}$ is $\begin{bmatrix} \lambda & \sigma \\ -\sigma & \lambda \end{bmatrix}$. Let us consider a general $M \in \R^{2\times m}$:

$$
  M = \begin{bmatrix} M_{11} & M_{12} & \dots & M_{1m} \\
                      M_{21} & M_{22} & \dots & M_{2m} \end{bmatrix}.
$$

We want this Givens matrix to be orthogonal. By homework exercise \@ref(exr:q507), we know this is the case when $\lambda^2 + \delta^2 = 1$. We also want $G^{(1,2)}M$ to be an upper triangular matrix. Since

$$
  G^{(i,j)} M =
    \begin{bmatrix}
      \lambda M_{11} + \sigma M_{12} & \dots & \lambda M_{1m} + \sigma M_{2m} \\
      -\sigma M_{11} + \lambda M_{12} & \dots & -\sigma M_{1m} + \lambda M_{2m} \\
    \end{bmatrix},
$$

we need $\lambda M_{12} = \sigma M_{11}$. So, solving these two equations, we find that $\lambda = \frac{M_{11}}{\sqrt{M_{11}^2 + M_{21}^2}}$ and $\sigma = \frac{M_{21}}{\sqrt{M_{11}^2 + M_{21}^2}}$. Hence, given the matrix $M$, we can find a Givens rotation which when multiplied by $M$ returns an upper triangular matrix.

This also means that given a vector $a \in \R^n$, we can find a Givens rotation such that $G^{(i,j)} a$ gives back $a$ except for one entry, which has been changed to $0$.

```

### "Large" Data Problem

Finally, we will take a look at how to solve a "large" data problem using QR decomposition. To do so, let $A \in \R^{n\times m}$ be a matrix with $n$ "big". By "big", we mean so large that $A$ won't fit in memory, but the first $m+1$ rows of $A$ will.

Gentleman published a few papers in 1973/1974 describing a method for incremental QR decomposition. The key ideas are as follows:

1) Remember that the solution to the linear model is $(A'A)^{-1}A'b = R^{-1}(Q'b)$.
2) The QR decomposition of $\begin{bmatrix}A & b\end{bmatrix}$ gives $\begin{bmatrix} R & Q'b \\ 0 & S \end{bmatrix}$ (ex. \@ref(exr:q407) and \@ref(exr:q408))

Now, if we do QR decomposition on the first $m+1$ rows of $A$ we get $\begin{bmatrix} \tilde{R}_{m+1} & \tilde{Q}_{m+1}'b_{m+1} \\ 0 & S_{m+1} \end{bmatrix}$. Now, add the next row of $A$ to get $\begin{bmatrix} \tilde{R}_{m+1} & \tilde{Q}_{m+1}'b_{m+1} \\ 0 & S_{m+1} \\ a_{m+2} & b_{m+2} \end{bmatrix}$. Hit this with the right Givens rotation to change entry $(m+1, 1)$ to $0$. This will give us something of the form $\begin{bmatrix} \tilde{R}_{m+2} & \tilde{Q}_{m+2}'b_{m+2} \\ 0 & S_{m+2} \end{bmatrix}$. Here, $\tilde{R}_{m+2}$ is still an upper triangular matrix with less than $m$ rows. Repeat the procedure until we've added all rows of $A$/elements of $b$.

## Singular Value Decomposition (SVD)

Outline:

I) Motivating problems
II) SVD and solutions
III) Existence and properties
IV) Random projections (a modern application of SVD)

### Motivating Problems

```{example, "Minimum Norm Linear System Solution", label = "svd-problem-1"}
Let $A \in \R^{n \times m}$ with $\text{rank}(A) < m \le n$, and let $B \in \text{range}(A)$. Find $x$ s.t.

$$
  x \in \argmin_{y \in \R^m} \left\{\norm{y}_2 : Ay = b \right \}
$$

```

```{example, "Matrix 2-norm", label = "svd-problem-2"}
Let $A \in \R^{n \times m}$. Find

$$
  \norm{A}_2 = \sup_{v \in \R^m\setminus\{0\}} \frac{\norm{Av}_2}{\norm{v}_2}.
$$

```

```{example, "Low rank matrix approximation (i.e. data compression)", label = "svd-problem-3"}
Let $A \in \R^{n\times m}$. Find $x$ s.t.

$$
  x = \argmin_{rank(Y) \le k}\norm{A-Y}_F.
$$

```

Note: $\norm{A}_F$ is the *Frobenius norm* and is defined as $\norm{A}_F = \left(\sum_{i=1}^m \sum_{j=1}^n |a_{ij}|^2 \right)^{1/2}$. So it is sort of a Euclideaon norm extended to matrices.

### SVD

#### SVD definition

```{theorem, "Singular Value Decomposition", label = 'svd'}
Suppose $A \in \R^{n\times m}$ and $n\ge m$. Then there exists $U \in \R^{n \times n}$ and $V \in \R^{m\times m}$ that are both orthogonal, and a diagonal matrix $\Sigma \in \R^{n \times m}$ with diagonal elements $\sigma_1 \ge \sigma_2 \ge \dots \ge \sigma_m \ge 0$ such that

$$ A = U \Sigma V'$$


```

Note:

* The diagonal elements of $\Sigma$ are called the singular values of $A$.
* The columns of $U$ are called the left singular vectors
* The columns of $V$ are called the right singular vectors

```{corollary, cor-svd}
$\text{rank}(A)$ is the number of non-zero singular values of $A$.
```


#### Solutions to motivating problems

```{solution, name = "Solution to example \\@ref(exm:svd-problem-1)"}

Since $b \in \text{range}(A)$, there exists a $y$ such that $Ay = b$. Now, by theorem \@ref(thm:svd) there exist $U$,$V$, and $\Sigma$ such that $A=U\Sigma V^\prime$. Since $U$ is orthogonal, $U^{-1} = U^\prime$. So,

$$\begin{aligned}
  U\Sigma V^\prime y &= b \Leftrightarrow \\
  \Sigma V^\prime y &= U^\prime b.
\end{aligned}$$

Let $z = V^\prime y$ and $c = U^\prime b$. By corollary \@ref(cor:cor-svd) we now that there are exactly $\text{rank}(A) = r$ non-zero singular values. So

$$\begin{aligned}
  \begin{bmatrix}
  \sigma_1 & & & & & \\
    & \ddots & & & & \\
    & & \sigma_r & & & \\
    & & & 0 & & \\
    & & & & \ddots & \\
    & & & & & 0 \\
  \end{bmatrix} \cdot
  \begin{bmatrix} z_1 \\ z_2 \end{bmatrix} = \begin{bmatrix} c_1 \\ 0 \end{bmatrix}.
\end{aligned}$$

So, $z_1 = \begin{bmatrix} \sigma_1^{-1} & & \\ & \ddots & \\ & & \sigma_r^{-1} \end{bmatrix} c_1$. We want to minimize $\norm{y}_2 = \norm{V^\prime z}_2 = \norm{z}_2 = \sqrt{\norm{z_1}_2^2 + \norm{z_2}_2^2}$. This is done by setting $z_2=0$, which we can do since $z_2$ does not affect the equation above. (It is multiplied by all the $0$ rows of $\Sigma$.) So, the minimum norm solution is

$$\begin{aligned}
  x &= V
    \begin{bmatrix}
      \sigma_1^{-1} & & & \\
      & \ddots & & \huge{c_1} \\
      & & \sigma_{r}^{-1} & \\
      & {\huge 0} & &
    \end{bmatrix} \\
    &= V \cdot V^\prime y.
\end{aligned}$$

```

For the solution to example \@ref(exm:svd-problem-2), we'll need the following result:

```{lemma}

Let $D$ be a non-zero diagonal matrix of size $n \times m$, $n\ge m$. Then, $$\norm{D}_2 = \max_i |D_{ii}|$$.

```

```{proof}
Note that $\norm{A}_2 = \max_{\norm{v}_2 = 1} \norm{Av}_2$. Also, if we let $D_{ii} = \max_{j} |D_{jj}|$ and $v$ be a vector with norm $1$,

$$
  \norm{Dv}_2^2 = \sum_{j=1}^m (D_{jj}^2 v_j)^2 \leq D_{ii}^2 \sum_{j=1}^m v_j^2 = D_{ii}^2 \norm{v}_2^2 = D_{ii}^2.
$$

Now, let $z \in \R^m$ such that $z_{ij} = \left\{ \begin{matrix} 0, & j \neq i \\ \frac{D_{ii}}{|D_{ii}|}, & j = i \end{matrix} \right .$. Then $\norm{z}_2 = \sqrt{\frac{D_{ii}^2}{|D_{ii}|^2}} = 1$, and

$$
  \norm{Dz}_2^2 = \sum_{j=1}^m (D_{jj} z_j)^2 = D_{ii}^2 \frac{D_{ii}^2}{|D_{ii}|^2} = D_{ii}^2.
$$

Since $\norm{z}_2 = 1$,

$$ D_{ii}^2 \norm{Dz}_2^2 \le (\max_{\norm{v}_2 = 1} |D_{ii}|)^2 \le D_{ii}^2$$,

so $\norm{D}_2 = \max_{\norm{v}_2 = 1} |D_{ii}| = |D_{ii}| = max_{j} |D_{jj}|$.

```

```{solution, name = "Solution to example \\@ref(exm:svd-problem-2)"}
First, use the SVD of $A$ to write $A = U \Sigma V^\prime$. Now, since the 2-norm is invariant under multiplication of orthogonal matrices, we have that

$$\begin{aligned}
  \norm{A}_2 &= \max_{\norm{v} = 2} \norm{U\Sigma V^\prime v}_2 \\
             &= \max_{\norm{v} = 2} \norm{\Sigma V^\prime v}_2.
\end{aligned}$$

If we let $z = V^\prime v$, we see that $\norm{z}_2 = \norm{v}_2 = 1$, since $V^\prime$ is an orthogonal matrix. Hence,

$$
  \norm{A}_2 = \max_{\norm{z}_2 = 1} \norm{\Sigma z}_2 = \norm{\Sigma}_2 = \max_{i} |\sigma_i| =  \sigma_1,
$$

where we used the lemma above to obtain the second to last equality.
```

```{solution, name = "Solution to example \\@ref(exm:svd-problem-3)"}
Recall, $A = \sum_{i=1}^n \sigma_i u_i v_i^\prime = U \Sigma V^\prime$. We want to find $\argmin_{\text{rank}(Y) \le k} \norm{A-Y}_F$.

Case 1: If $\text{rank}(A) \le k$, then $Y = A$ is the solution.

Case 2: $\text{rank}(A) > k$. Since the Frobenius norm is orthogonally invariant, we can obtain that

$$\begin{aligned}
  \norm{A-Y}_F^2 &= \norm{U\Sigma V^\prime - Y}_F^2 \\
                 &= \norm{\Sigma - U^\prime Y V}_F^2.
\end{aligned}$$

If we let $X = U^\prime Y V$, we get that

$$\begin{aligned}
  \norm{A-Y}_F^2 &= \sum_{i=1}^n \sum_{j=1}^m (\sigma_{ij} - x_{ij})^2 \\
                 &= \sum_{i=1}^n \sum_{j=1,i\ne j}^m ( - x_{ij})^2  + \sum_{i=1}^n (\sigma_i - x_{ij})^2,
\end{aligned}$$

since $\sigma_{ij}=0$ for all $i \ne j$, and at most $k$ of the $\sigma_{ii}$ are non-zero. To minimize the expression above, we choose $Y$ such that $x_{ij}=0$ for $i\ne j$, and $x_{ii} = \sigma_i$. Hence,

$$
  X = \begin{bmatrix} \sigma_1 & & & & & \\
                      & \ddots & & & & \\
                      & & \sigma_k & & & \\
                      & & & 0 & & \\
                      & & & & \ddots & \\
                      & & & & & 0 \end{bmatrix},
$$

and $Y = U X V^\prime$.

```

### Existence and Properties

```{proof, name = "SVD (\\@ref(thm:svd))"}
Recall that $\norm{A}_2 = \sup_{v \ne 0} \frac{\norm{Av}_2}{\norm{v}_2} = \max_{\norm{v}_2 = 1} \norm{Av}_2$. I.e. there exists a $v_1$ such that $\norm{v_1}_2 = 1$ and $\norm{A}_2 = \norm{Av_1}_2$.

Let $u_1$ be a vector such that $\norm{A}_2 u_1 = Av_1$. This implies that $\norm{u_1}_2 = 1$, since $\norm{\norm{A}_2u_1}_2 = \norm{A}_2 \norm{u_1}_2 = \norm{Av_1}_2 = \norm{A}_2$.

Let $\sigma_1 = \norm{A}_2$. So, $\sigma_1 u_1 = A v_1$. Using the Gram-Schmidt procedure, we can create a matrix $V_1 \in \R^{n\times (n-1)}$ and $\tilde{U}_1 = \begin{bmatrix} u_1 V_1 \end{bmatrix} \in \R^{n \times n}$ being an orthogonal matrix. Similarly, we can create $\tilde{V}_1 \in \R^{m\times m}$ such that $\tilde{V}_1 = \begin{bmatrix} v_1 V_1 \end{bmatrix} \in \R^{m \times m}$ is orthogonal.

Now, $A \tilde{V}_1 = \begin{bmatrix} Av_1 & AV_1 \end{bmatrix} = \begin{bmatrix} \sigma_1 u_1 & AV_1 \end{bmatrix}$. Hence, $\tilde{U}_1^\prime A \tilde{V}_1 = \begin{bmatrix} u_1 \\ U_1^\prime \end{bmatrix} \begin{bmatrix} \sigma_1 u_1 & A V_1 \end{bmatrix} = \begin{bmatrix} \sigma_1 & w^\prime \\ 0 & \tilde{A} \end{bmatrix}$, since $u_1$ is orthogonal to all columns of $U_1^\prime$. We need to show that $w=0$. Since the 2-norm is orthogonally invariant, it holds for any $z \ne 0$,

$$\begin{aligned}
  \sigma_1^2 &= \norm{A}_2^2 \\
             &= \norm{\tilde{U}_1^\prime A \tilde{V}_1}_2^2 \\
             &= \norm{\begin{bmatrix} \sigma_1 & w^\prime \\ 0 & \tilde{A} \end{bmatrix}}_2^2 \\
             &\ge \frac{\norm{\begin{bmatrix} \sigma_1 & w^\prime \\ 0 & \tilde{A} \end{bmatrix} z}_2^2}{\norm{z}_2^2}.
\end{aligned}$$

Let $z = \begin{bmatrix} \sigma_1 \\ w \end{bmatrix}$. Then,

$$
  \sigma_1^2 \ge \frac{\norm{\begin{bmatrix} \sigma_1 & w^\prime \\ 0 & \tilde{A} \end{bmatrix} \begin{bmatrix} \sigma_1 \\ w \end{bmatrix}}_2^2}{\norm{\begin{bmatrix} \sigma_1 \\ w \end{bmatrix}}_2^2} = \frac{(\sigma_1^2 + \norm{w}_2^2)^2 + \norm{\tilde{A}w}_2^2}{\sigma_1^2 + \norm{w}_2^2}\ge \sigma_1^2 + \norm{w}_2^2 \ge \sigma_1^2,
$$

i.e. $\norm{w}_2^2 = 0$. So,

$$
  \tilde{U}_1 A V_1 = \begin{bmatrix} \sigma_1 & 0 \\ 0 & \tilde{A} \end{bmatrix}.
$$

Repeat the same procedure to get $U, V$ such that $A = U^\prime \Sigma V$.
```

```{corollary}
$\text{rank}(A)$ is exactly the number of non-zero singular values of $A$.
```

```{proof}

$\text{rank}(A) = \text{rank}(U \Sigma V^\prime ) = \text{rank}(\Sigma) =$ number of non-zero diagonal elements.

```

```{corollary, sigma-min-max}
Let $A,E \in \R^{n\times m}$, $\sigma_{\text{max}}$ ($\sigma_{\text{min}}$) denote the largest (smallest) singular value of A. Then

$$
  \sigma_{\text{max}}(A+E) \le \sigma_{\text{max}}(A) + \norm{E}_2
$$

and

$$
  \sigma_{\text{min}}(A+E) \ge \sigma_{\text{min}}(A) - \norm{E}_2.
$$

```

```{corollary, name = "Hoffman-Wielandt Inequality", label = "hoffman-wielandt"}
Let $A,E \in \R^{n \times m}$, $\sigma_k(\dot)$ denote the k'th largest singular value. Let $p =\min(m,n) \le \norm{E}_F^2$. Then

$$
  \sum_{k=1}^p (\sigma_k(A+E) - \sigma_k(A))^2 \le \norm{E}_F^2.
$$

```

```{corollary, for-q703}

Let $r = \text{rank}(A)$.

1) $\text{range}(A) = \text{span}(u_1, \ldots, u_r)$
2) row space of A $= \text{span}(v_1, \ldots, v_r)$
3) $\text{null}(A) = \text{span}(v_{r+1}, \ldots, v_{m})$
4) $\text{null}(A^\prime) = \text{span}(u_{r+1}, \ldots, u_{m})$

Moreover,

1) $U_r = \begin{bmatrix} u_1 & \cdots & u_r \end{bmatrix}$, $U_r U_r^\prime = P_{\text{range}(A)}$
2) $U_{n-r} = \begin{bmatrix} u_{r+1} & \cdots & u_n \end{bmatrix}$, $U_{n-r} U_{n-r}^\prime = P_{\text{null}(A)}$
3) $V_r = \begin{bmatrix} v_1 & \cdots & v_r \end{bmatrix}$, $V_r V_r^\prime = P_{\text{row}(A)}$
2) $V_{n-r} = \begin{bmatrix} v_{r+1} & \cdots & v_n \end{bmatrix}$, $V_{n-r} V_{n-r}^\prime = P_{\text{null}(A)}$

where $P_{\mathcal{B}}$ is the projection onto the space $\mathcal{B}$. 
```


```{definition, name = 'Pseudo-inverse', label = 'pseudo-inverse'}
For a matrix $A \in \R^{n\times m}$, we call $A^+ \in \R^{m\times n}$ a pseudo-inverse to $A$ if 

1) $AA^+A = A$
2) $A^+AA^+ = A^+$
3) $(AA^+)^\prime = AA^+$
4) $(A^+A)^\prime = A^+A$

```

```{theorem}
For any matrix $A \in \R^{n \times m}$, there exists a unique pseudo-inverse $A^+$.
```

```{proof}
Suppose $B$ and $C$ are both pseudo-inverses of $A$. Then 

$$\begin{aligned}
  BA &= B(ACA) \\
     &= (BA)(CA) \\
     &= (BA)^\prime (CA)^\prime \\
     &= A^\prime B^\prime A^\prime C^\prime \\
     &= (ABA)^\prime C^\prime \\
     &= A^\prime C^\prime \\
     &= (CA)^\prime \\
     &= CA.
\end{aligned}$$

Similarly,

$$\begin{aligned}
  AB &= (ACA)B \\
     &= (AC)(AB) \\
     &= (AC)^\prime (AB)^\prime \\
     &= C^\prime A^\prime B^\prime A^\prime \\
     &= C^\prime (ABA)^\prime \\
     &= C^\prime A^\prime \\
     &= (AC)^\prime \\
     &= AC.
\end{aligned}$$
  
So, $B = BAB = CAB = CAC = C$. This shows that if there exists a pseudo-inverse, it is unique.
  
  
Now, let $D \in \R^{n\times m}$ be a diagonal matrix with $d_{ii}$ its diagonal elements. Then the diagonal matrix $E \in \R^{m\times n}$ with diagonal elements $d_{ii}^{-1}$ for $d_{ii} \neq 0$ and $0$ otherwise is the pseudo-inverse of $D$. 

So,

$$[DE]_{ij} = \sum_{k=1}^m D_{ik} E_{kj} = \left\{\begin{array}{rl} 0, & i \neq j \\ 1, & i = j, d_{ii} \neq 0 \\ 0, & i = j, d_{ii} = 0 \end{array} \right .$$

and 

$$[ED]_{ij} = \sum_{k=1}^n D_{ik} E_{kj} = \left\{\begin{array}{rl} 0, & i \neq j \\ 1, & i = j, d_{ii} \neq 0 \\ 0, & i = j, d_{ii} = 0 \end{array} \right .$$

Since $ED$ and $DE$ are both diagonal matrices, $(ED)^{\prime} = ED$ and $(DE)^{\prime} = DE$. 

Furthermore, 

$$[DED]_{ij} = \sum_{k=1}^n D_{ik}[ED]_{kj} = \left\{\begin{array}{rl} 0, & i \neq j \\ D_{ij}, & i = j \end{array} \right .$$

and  

$$[EDE]_{ij} = \sum_{k=1}^n E_{ik}[DE]_{kj} = \left\{\begin{array}{rl} 0, & i \neq j \\ E_{ij}, & i = j \end{array} \right .$$

So $E$ satisfies the four conditions of a pseudo-inverse. I.e. for any diagonal matrix, there exists a pseudo-inverse.

Now, we know that there exist $U,\Sigma, V$ such that $A = U\Sigma V^\prime$. Let $B = V \Sigma^+ U^\prime$. Recall that $U^\prime U = I$ and $V^\prime V = I$. 

1) $ABA = U\Sigma V^\prime V \Sigma^+ U^\prime U\Sigma V^\prime = U \Sigma \Sigma^+ \Sigma V^\prime = U \Sigma V^\prime = A$
2) $BAB = V \Sigma^+ U^\prime U \Sigma V^\prime V \Sigma^+ U = V \Sigma^+ \Sigma \Sigma^+ U^\prime = V \Sigma^+ U^\prime = B$
3) 

$$\begin{aligned} 
  (AB)^\prime = B^\prime A^\prime &= (V \Sigma^+ U^\prime)^\prime (U \Sigma V^\prime)^\prime \\
                                  &= U (\Sigma^+)^\prime V^\prime V \Sigma^\prime U^\prime \\
                                  &= U (\Sigma \Sigma^+)^\prime U^\prime \\
                                  &= U \Sigma \Sigma^+ U^\prime \\
                                  &= U \Sigma V^\prime V \Sigma^+ U^\prime \\
                                  &= AB
\end{aligned}$$

4) 

$$\begin{aligned} 
  (BA)^\prime = A^\prime B^\prime &= (U \Sigma V^\prime)^\prime (V \Sigma^+ U^\prime)^\prime \\
                                  &= V \Sigma^\prime U^\prime U (\Sigma^+)^\prime V^\prime \\
                                  &= V (\Sigma^+ \Sigma)^\prime V^\prime \\
                                  &= V \Sigma^+ \Sigma V^\prime \\
                                  &= V \Sigma^+ U^\prime U \Sigma V^\prime \\
                                  &= BA.
\end{aligned}$$

So, $B$ is a pseudo-inverse of $A$. 
                                  
Hence, any matrix has a unique pseudo-inverse.

```

### Random Projections

Let $A \in \R^{n\times m}$, $m >> n$. When this is the case, it is very hard to compute the SVD. So instead we try to find a matrix $C$ with $\text{range}(C) \approx \text{range}(A)$. In other words, $A \approx P_{\text{range}(C)}A$. One way to find such a $C$ is to simply sample columns from $A$. 

```{theorem}
Suppose $A \in \R^{n \times m}$, $C$ is as in the algorithm `inexactRankK` (see [here]('../Lecture scripts/Singular Value Decomposition.jl')), and $H$ is the $k$ left singular vectors of $C$. Then

$$\norm{A-HH^\prime A}_F^2 \le \norm{A-A_k}_F^2 + 2\sqrt{k} \norm{AA^\prime - CC^\prime}_F,$$

where $A_k$ is the rank $k$ approximation of $A$.
```

```{proof}
Recall that $\norm{A}_F^2 = \text{tr}(A^\prime A)$, and $H^\prime H = I$, since the columns of $H$ are singular vectors, i.e. are orthogonal to each other. 

$$\begin{aligned}
  \norm{A - HH^\prime A}_F^2 &= \text{tr}((A-HH^\prime A)^\prime (A-HH^\prime A)) \\
                            &= \text{tr}((A^\prime - A^\prime H H^\prime)(A-HH^\prime A)) \\
                            &= \text{tr}(A^\prime A - A^\prime H H^\prime A - A^\prime HH^\prime A + A^\prime H H^\prime HH^\prime A) \\
                            &= \text{tr}(A^\prime A - A^\prime H H^\prime A) \\
                            &= \text{tr}(A^\prime A) - \text{tr}(A^\prime H H^\prime A) \\
                            &= \norm{A}_F^2 - \norm{A^\prime H}.
\end{aligned}$$

Since

$$
  \norm{A}_F^2 = \norm{A-A_k}_F^2 + \sum_{j=1}^k \sigma_j^2(A),
$$

we have that
  
$$\begin{aligned}
  \norm{A-H H^\prime A}_F^2 &= \norm{A-A_k}_F^2 + \sum_{j=1}^k \sigma_j^2(A) - \norm{A^\prime H}_F^2 \\
                            &= \norm{A-A_k}_F^2 + \sum_{j=1}^k \left[\sigma_j^2(A) - \sigma_j^2(C)\right] + \sum_{j=1}^k \sigma_j^2{C} - \norm{A^\prime H}_F^2. 
\end{aligned}$$

Note that, using the Cauchy-Schwarts inequality, we get

$$\begin{aligned}
  \sum_{j=1}^k \left[\sigma_j^2(A) - \sigma_j^2(C)\right] &= \left | \begin{bmatrix} 1 \\ \vdots \\ 1 \end{bmatrix} \cdot \begin{bmatrix} \sigma_1^2(A) - \sigma_1^2(C) & \cdots & \sigma_k^2(A) - \sigma_k^2(C) \end{bmatrix} \right | \\
                                                          &\le \sqrt{\norm{\begin{bmatrix} 1 \\ \vdots \\ 1 \end{bmatrix}} \norm{\begin{bmatrix} \sigma_1^2(A) - \sigma_1^2(C) & \cdots & \sigma_k^2(A) - \sigma_k^2(C) \end{bmatrix}}} \\
                                                          &= \sqrt{k} \sqrt{\sum_{j=1}^k \left(\sigma_j^2(A) - \sigma_j^2(C)\right)^2} \\
                                                          &\le \sqrt{k} \sqrt{\sum_{j=1}^k \left(\sigma_j(AA^\prime) - \sigma_j(CC^\prime)\right)^2} \\
                                                          &= \sqrt{k} \sqrt{\sum_{j=1}^k \left(\sigma_j(CC^\prime + AA^\prime - CC^\prime) - \sigma_j(CC^\prime)\right)^2} \\
                                                          &\le \sqrt{k} \norm{AA^\prime - CC^\prime}_F.
\end{aligned}$$
  
If $H_1, \ldots, H_k$ denote columns of $H$, then $A^\prime H = \begin{bmatrix} A^\prime H_1 & \cdots & A^\prime H_k \end{bmatrix}$. Since 

$$
  \norm{A^\prime H}_F^2 = \sum_{j=1}^k \norm{A^\prime H_j}_2^2,
$$
  
we can use Cauchy-Schwartz as above to obtain that
    
$$\begin{aligned}
  \sum_{j=1}^k \sigma_j^2(C) - \norm{A^\prime H}_F^2 &\le \sqrt{k} \sqrt{\sum_{j=1}^k \left[\sigma_j{CC^\prime} - H_j^\prime A A^\prime H_j\right]^2} \\
                                                     &= \sqrt{k} \sqrt{\sum_{j=1}^k \left[H_j^\prime CC^\prime H_j - H_j^\prime A A^\prime H_j\right]^2} \\
                                                     &\le \sqrt{k} \norm{AA^\prime - CC^\prime}_F,
\end{aligned}$$
  
where we in the last step use the Hoffman-Wielandt inequality (corollary \@ref(cor:hoffman-wielandt)). 
  
Combining all of this, we get

$$
  \norm{A - HH^\prime A}_F^2 \le \norm{A-A_k}_F^2 + 2\sqrt{k} \norm{AA^\prime - CC^\prime}_F.
$$

```


## Iterative Methods 

### Overview 

First, some references:

a) Golub and Van Loan
b) Saad (2000): *Iterative methods for sparse linear systems* [link](https://www-users.cs.umn.edu/~saad/IterMethBook_2ndEd.pdf)
c) Shewchuk (1994): *Introduction to Conjugated Gradients without the Agonizing Pain* [link](https://www.cs.cmu.edu/~quake-papers/painless-conjugate-gradient.pdf)
d) Gower and Richtarik (2015): *Randomized Iterative Methods for Linear Systems* [link](https://arxiv.org/abs/1506.03296)

### Outline

We will be going throuh the following:

i) Why iterative methods?
ii) Splitting Methods
iii) Randomized Kaezmarz Method
iv) Gradient Descent
v) Conjugated Gradients
vi) GMRES (optional)

### Motivation

These methods have had a great impact historically speaking. They take advantage of any sparsity found in a matrix, making them "easier" computational. 

When working with huge systems (such as weather prediction, computational chemistry, genomics, etc), this is the way to deal with it.

### Splitting Methods

Let $A$ be a matrix, and $b$ a vector. Let

- $x^c$ denote the current iterate
- $x^+$ denote the next iterate
- $r^c$ denote the current residual
- $r^+$ denote the next residual

where $r^c = Ax^c - b$ and $r^+ = Ax^+ - b$. The goal is to find methods to minimize the residual by iteratively defining $x^+$ based on $x^c$. 

A splitting method takes a matrix $A$ and splits it. One way of doing so is by splitting $A$ into three parts $A = D - E - F$, where

* $D$ is the diagonal
* $E$ is the negative lower triangular part of $A$ excluding the diagonal
* $F$ is the negative upper triangular part of $A$ excluding the diagonal

Based on this split, there are a few different ways to iteratively update $r^+$.

```{definition, name = "The Jacobi Method"}
*The Jacobi Method* finds $x^+$ from $x^c$ using the following rule:
  
$$x_i^+ = \frac{b_i - \sum_{k\neq i}A_{ik}x_k^c}{A_{ii}}.$$

If we do this for all $i$, we can write this in matrix form:
  
$$x^+ = D^{-1}(b + (E+F)x^c).$$

```

For the Jacobi Method, we can see that $r_i^+ = 0:$

$$\begin{aligned}
  x_i^+ &= \frac{b_i - \sum_{k\neq i}A_{ik}x_k^c}{A_{ii}} \iff \\
  A_{ii}x_i^+ &= b_i - \sum_{k\neq i}A_{ik}x_k^c \iff \\
  0 &= b_i - \sum_{k\neq i}A_{ik}x_k^c - A_{ii}x_i^+ = b_i - \sum_{k}A_{ik}x_k^c = r_i^+.
\end{aligned}$$

```{definition, name = "The Gauss-Seidel Method"}
*The Gauss-Seidel Method* finds $x^+$ from $x^c$ using the following rule: 
  
$$x_i^+ = \frac{1}{A_ii}\left(b_i - \sum_{k=1}^{i-1} A_{ik}x_k^+ - \sum_{k=i+1}^d A_{ik} x_k^c\right),$$

which in matrix formulation is 

$$x^+ = D^{-1}(b + Ex^+ + Fx^c)$$,

or equivalently

$$x^+ = (D-E)^{-1}(b + Fx^c).$$

```

As for the Jacobi method, it can be seen that $r_i^+ = 0$.

```{definition, name = "Successive Over Relaxation (SOR)"}

When we update $x^c$ to $x^+$ using a rule of the form 

$$ (D-\omega E)x^+ = (\omega F + (1-\omega)D)x^c + \omega b,$$

it is called a *Successive Over Relaxation* method. 
  
```

Note: if we pick $\omega = 1$, we get back the Gauss-Seidel method.

```{definition, name = "Backward SOR"}

The following is called the *Backward SOR*:

$$ (D-\omega E)x^+ = (\omega F + (1-\omega)D)x^c + \omega b,$$

```

```{definition, name = "Symmetric SOR"}

The *Symmetric SOR* is a method where we first find $z$ based on the rule 

$$(D-\omega F)z = (\omega F + (1-\omega)D)x^c+\omega b$$

before using the rule

$$(D- \omega F)x^+ = (\omega F + (1-\omega)D)z + \omega b$$
  
to find $x^+$. 
  
```

### Convergence

All of the schemes mentioned above are of the form $x^+ = G x^c + f$:

* **Jacobi**: $G = D^{-1}(E+F)$, $f = D^{-1}b$.

* **Gauss-Seidel**: $G = (D-E)^{-1}F$, $f = (D-E)^{-1} b$.

* **SOR**: $G = (D - \omega E)^{-1}(\omega F + (1- \omega)D)$, $f = \omega (D-\omega E)^{-1} b$.

Now, if we assume that $x^*$ is a vector such that $Ax^* = b$, then $(I-G)x^* = f$: (for the following, keep in mind that $A = D - E - F$)

* **Jacobi**: 

$$\begin{aligned} 
  f &= D^{-1}b \\ 
    &= D^{-1}Ax^* \\
    &= D^{-1}(D-E-F)x^* \\
    &= (DD^{-1} - D^{-1}(E+F))x^*\\
    &= (I - G)x^*.
\end{aligned}$$

* **Gauss-Seidel**:

$$\begin{aligned}
  f &= (D-E)^{-1}b \\
    &= (D-E)^{-1}Ax^* \\
    &= (D-E)^{-1}(D-E-F)x^* \\
    &= ((D-E)^{-1}(D-E)-(D-E)^{-1}F)x^* \\
    &= (I - G)x^*.
\end{aligned}$$

* **SOR**:

$$\begin{aligned}
  f &= \w (D-\w E)^{-1}b\\
    &= \w (D-\w E)^{-1}Ax^* \\
    &= \w (D-\w E)^{-1}(D-E-F)x^* \\
    &= (D-\w E)^{-1}(\w D-\w E-\w F)x^* \\
    &= (D-\w E)^{-1}(D - D + \w D-\w E-\w F)x^* \\
    &= (D-\w E)^{-1}(D -\w E - [(1-\w)D + \w F])x^* \\
    &= ((D-\w E)^{-1}(D -\w E) - (D-\w E)^{-1}[D(1-\w) + \w F])x^* \\
    &= (I - G)x^*.
\end{aligned}$$


```{lemma, label = "next-current-diff"}
For the Jacobi, Gauss-Seidel, and SOR methods, if there exists a $x^*$ s.t. $Ax^* = b$, then $x^+ - x^* = G(x^c - x^*)$.
```

```{proof}

We just saw that $Ax^* = b$ implies $(I-G)x^* = f$. We also saw that $x^+ = Gx^c + f$. Hence

$$\begin{aligned}
  x^+ &= G x^c + f \\
      &= G x^c + (I-G)x^* \\
      &= G x^c + x^* - Gx^* \iff \\
  x^+ - x^* &= G(x^c - x^*).
\end{aligned}$$
    
```


```{theorem}

Suppose there exists a $x^*$ s.t. $A x^* = b$. Let $x_0$ be arbitrary and define a sequence $\{x_k\}_{k \in \N}$ by 

$$
  x_k = Gx_{k-1} + f.
$$
  
If $\rho(G) < 1$, then $x^*$ is unique, and $x_k \rightarrow x^*$ as $k \rightarrow \infty$. 
 
```

In the theorem above, $\rho(G)$ is the spectral radius of the matrix $G$. This is defined as the largest eigenvalue of the matrix $G$. 

```{definition, name = "Jordan Canonical Form", label = "jordan"}
Let $A \in \R^{n \times n}$. There exists an $X$ which is invertible, and a block-diagonal matrix $J$, whose blocks are of the form $\lambda I + E$, where $\lambda$ is an eigenvalue of $A$, and 

$$
  E = \left\{ \begin{array}{rl} 1, & j = i+1 \\ 0, & \text{ otherwise} \end{array} \right .
$$
    
such that $A = XJX^{-1}$.

```

### Randomized Kaczmarz Method

Consider $Ax = b$. Let the rows of $A$ be denoted as $a_1^\prime, a_2^\prime, \dots, a_n^\prime$, and $b = (b_1, \dots, b_n)^\prime$. Now, the goal is to choose the next iteration of $x$ such that $r^+ = b_i - a_i^\prime x^+ = 0$. Let's say we try to set $x^+ = x^c + v$ for some appropriate $v$. What should $v$ be then? We want $b_i = a_i^\prime (x^c + v)$, which would imply that $a_i^\prime v = b_i - a_i^\prime x^c$. This has many possible solutions. So let's look for a particular one, namely one that is proportional to $a_i$: $v=\alpha a_i$. Then $\alpha \norm{a_i}_2^2 = b_i - a_i^\prime x^c$ which implies $\alpha = \frac{b_i - a_i^\prime x^c}{\norm{a_i}_2^2}$. 

The above approach gives us Kaczmarz Method: the next iterate of $x$ is $x^+ = x^c + \frac{b_i - a_i^\prime x^c}{\norm{a_i}_2^2}a_i$. 

Now, the *Randomized* Kaczmarz Method is the one where we randomly choose which column to use for the next iteration based on the probability distribution over all columns of $A$ given by $P(i = l) = \frac{\norm{a_l}_2^2}{\norm{A}_F^2}$. The following theorem guarantees us that this approach actually works, i.e. we converge towards the solution of $Ax = b$.

```{theorem, name = "Randomized Kaczmarz Method", label = "rand-kaczmarz"}
Suppose $A \in \R^{n\times m}$ is invertible and $x^* = A^{-1}b$. 

Given a sequence of i.i.d. random variables $i_1, i_2, \dots$ ($P(i_k = l) = \frac{\norm{a_l}_2^2}{\norm{A}_F^2}$), and $x_0$ an arbitrary initial value, define 

$$ x_k = x_{k-1} + \frac{b_{i_{k-1}}-a_{i_{k-1}}^\prime x_{k-1}}{\norm{a_{i_{k-1}}}_2^2}a_{i_{k-1}}$$
  
for all $k > 1$. Then

$$E\left[\norm{x_k - x^*}_2^2 \right] \leq \left(1-\frac{\sigma_{min}(A)^2}{\norm{A}_F^2}\right)^k \norm{x_0 - x^*}_2^2.$$

```

Note that the above result (by Chebyshev) implies 

$$P\left[\norm{x_k - x^*}_2 > \epsilon \right] \leq \frac{1}{\epsilon^2}E\left[\norm{x_k - x^*}_2^2\right]$$

which in turn implies $x_k \rightarrow_p x^*$ as $k \rightarrow \infty$.

```{proof}
First of all, note that since $i_k$ is independent of $i_{l}$ for all $l < k$, $i_k$ is independent of all $x_l$ for all $l < k$. 

**Observation 1:** $x_{k+1} - x_k$ is orthogonal to $x_{k+1} - x^*$. Therefore $$\norm{x_{k+1} - x^*}_2^2 = \norm{x_{k} - x^*}_2^2 - \norm{x_{k+1}-x_k}_2^2.$$

Since $b_{i_k} = a_{i_k}^\prime x^*$, we have that 

$$\begin{aligned}
  x_{k+1} - x_k &= \frac{b_{i_k}-a_{i_k}^\prime x_k}{\norm{a_{i_k}}_2^2}a_{i_k} \\
                &= \frac{a_{i_k}^\prime x^*-a_{i_k}^\prime x_k}{\norm{a_{i_k}}_2^2}a_{i_k} \\
                &= \frac{a_{i_k}^\prime (x^*- x_k)}{\norm{a_{i_k}}_2^2}a_{i_k}.
\end{aligned}$$

So

$$\begin{aligned}
  \norm{x_{k+1} - x_k}_2^2  &= \norm{a_{i_k}}_2^2 \frac{[a_{i_k}^\prime (x_k - x^*)]^2}{\norm{a_{i_k}}_2^4} \\
                            &= \frac{[a_{i_k}^\prime (x_k - x^*)]^2}{\norm{a_{i_k}}_2^2}.
\end{aligned}$$

    
**Observation 2:** For any vector $y \in \R^n$ it holds that 
  
$$E\left(\frac{(a_{i_0}^\prime y)^2}{\norm{a_{i_0}}_2^2}\right) \geq \frac{\sigma_{min}^2(A)}{\norm{A}_F^2} \norm{y}_2^2.$$

"Proof:"
  
Recall that $\norm{A}_2^2 = \max_{y \neq 0} \frac{\norm{Ay}_2^2}{\norm{y}_2^2} = \sigma_{max}(A)^2 >= \sigma_{min}(A)^2$. With this in mind

$$\begin{aligned}
  \sum_{i=1}^n (a_i^\prime y)^2 &= \norm{Ay}_2^2 \ge \sigma_{min}(A)^2 \norm{y}_2^2.
\end{aligned}$$
  
Divide through by $\norm{A}_F^2$ to get $\sum_{i=1}^n \frac{1}{\norm{A}_F^2}(a_i^\prime y)^2 \ge \frac{\sigma_{min}(A)^2}{\norm{A}_F^2} \norm{y}_2^2$, before we simply multiply each term in the sum by $1 = \frac{\norm{a_i}_2^2}{\norm{a_i}_2^2}$. So

$$\begin{aligned}
  \frac{\sigma_{min}(A)^2}{\norm{A}_F^2} \norm{y}_2^2 &\le \sum_{i=1}^n \frac{\norm{a_i}_2^2}{\norm{A}_F^2}\frac{(a_i^\prime y)^2}{\norm{a_i}_2^2} \\
                                                      &= \sum_{i=1}^n P(i_0 = i) \frac{(a_i^\prime y)^2}{\norm{a_i}_2^2} \\
                                                      &= E\left(\frac{(a_{i_0}^\prime y)^2}{\norm{a_{i_0}}_2^2}\right).
\end{aligned}$$


  
Now, using these two observations together:
  
$$\begin{aligned}
  E\left[\norm{x_{k+1} - x^*}_2^2 | x_k \right ] &= E\left[\norm{x_k - x^*}_2^2 | x_k\right] - E\left[ \norm{x_{k+1} - x_k}_2^2 | x_k \right] \\
                                                 &= \norm{x_k - x^*}_2^2 - E\left[ \frac{(a_{i_k}^\prime (x_k - x^*))^2}{\norm{a_{i_k}}_2^2} \right] \\
                                                 &\le \norm{x_k - x^*}_2^2 - \frac{\sigma_{min}(A)^2}{\norm{A}_F^2} \norm{x_k - x^*}_2^2 \\
                                                 &= (1 - \frac{\sigma_{min}(A)^2}{\norm{A}_F^2})\norm{x_k - x^*}_2^2.
\end{aligned}$$
    
Finally, taking expectation on both sides gives us that $E\left[\norm{x_{k+1} - x^*}_2^2\right] \le \left(1 - \frac{\sigma_{min}(A)^2}{\norm{A}_F^2}\right)E\left[\norm{x_k - x^*}_2^2\right]$. This upper bound holds for any $k$, so we can repeatedly use this to get
  
$$
  E\left[\norm{x_{k+1} - x^*}_2^2\right] \le \left(1 - \frac{\sigma_{min}(A)^2}{\norm{A}_F^2}\right)^k \norm{x_0 - x^*}_2^2
$$
    
since $E[\norm{x_0 - x^*}_2^2] = \norm{x_0 - x^*}_2^2$.
  
```

### Gradient Descent

The Gradient Descent iterative method updates the current $x^c$ to $x^+$ by 

\begin{align}
  x^+ &= x^c + \alpha \sum_{i=1}^n a_i (b_i - a_i x^c) \\
      &= x^c + \alpha A^\prime (b - Ax^c)
\end{align}

The question now is: how do we choose $\alpha$? 

**Strategy 1**

Choose the $\alpha$ that minimizes $\norm{r^+}_2^2 = \norm{Ax^+ - b}_2^2$. 

```{lemma}

$$\argmin_\alpha \norm{r^+}_2^2 = \frac{\norm{A^\prime r^c}_2^2}{\norm{AA^\prime r^c}_2^2}$$

```

```{proof}
First, note that by homework exercise \@ref(exr:q1102), $A^\prime r^c \neq 0$, since if this were the case, the problem would be solved already. 

$$
  \norm{r^+}_2^2 = \norm{r^c}_2^2 - 2\alpha \norm{A^\prime r^c}_2^2 + \alpha^2 \norm{AA^\prime r^c}_2^2,
$$
  
since $r^+ = Ax^+ - b = A(x^c + \alpha A^\prime (b - Ax^c)) - b = Ax^c - b - \alpha A A^\prime ( Ax^c - b) = r^c - \alpha A A^\prime r^c$, and $\norm{r^+}_2^2 = (r^+)^\prime r^+$.

Differentiate this equation with respect to $\alpha$, equate to $0$, and solve for $\alpha$ will yield the result.
```

```{theorem, grad-descent}
Suppose $A$ is invertible. Given $x_0 \R^n$, let $x_k$ be defined as 

$$x_k = x_{k-1} + \alpha_{k-1}A^\prime (b-Ax_{k-1}),$$ 
  
where

$$ \alpha_k = \frac{\norm{A^\prime r_k}_2^2}{\norm{AA^\prime r_k}_2^2}.$$
  
Then 

$$
  \norm{r_k}_2^2 \le \left(1 - \frac{4\sigma_1^2 \sigma_n^2}{\sigma_1^2 + \sigma_n^2}\right)^k \norm{r_0}_2^2.
$$

```

```{proof}

$$\begin{aligned}
  \norm{r_{k+1}}_2^2 &= \norm{r_k}_2^2 - \alpha_k 2\norm{A^\prime r_k}_2^2 + \alpha_k^2 \norm{AA^\prime r_k}_2^2 \\
                     &= \norm{r_k}_2^2 - \frac{\norm{A^\prime r_k}_2^4}{\norm{A A^\prime r_k}_2^2} \\
                     &= \norm{r_k}_2^2 \left(1 - \frac{\norm{A^\prime r_k}_2^4}{\norm{r_k}_2^2 \norm{AA^\prime r_k}_2^2}\right).
\end{aligned}$$

If we let $A = U\Sigma V^\prime$ be the SVD of $A$, then

$$\begin{aligned}
  1 - \frac{\norm{A^\prime r_k}_2^4}{\norm{r_k}_2^2 \norm{AA^\prime r_k}_2^2} &= 1 - \frac{\norm{\Sigma U^\prime r_k}_2^4}{\norm{U^\prime r_k}_2^2 \norm{\Sigma \Sigma^\prime U^\prime r_k}_2^2} \\
    &= 1 - \frac{\norm{w}_2^4}{\norm{\Sigma^{-1}w}_2^2 \norm{\Sigma w}_2^2}.
\end{aligned}$$
  
We want to find an upper bound on $\norm{\Sigma^{-1}u}_2^2 \norm{\Sigma u}_2^2$ for any unit vector $w$. 

$$\begin{aligned}
  \norm{\Sigma^{-1}u}_2^2 \norm{\Sigma u}_2^2 &= \left( \sum_{i=1}^k \frac{u_i^2}{\sigma_i^2} \right) \left( \sum_{i=1}^n \sigma_i^2 u_i^2\right) \\
  \le \frac{(\sigma_1^2 + \sigma_n^2)^2}{4\sigma_1^2 \sigma_n^2},
\end{aligned}$$
  
where the last inequality is the Kontorovich inequality (see homework \@ref(exr:q1104)).

```

**Strategy 2**

Choose $\alpha = \argmin_\alpha \norm{x_{k+1} - x^*}_2^2$. 

**Strategy 3**

Note that $\norm{r^+}_2 = \norm{(I - \alpha A A^\prime)r^c}_2 \le \norm{I-\alpha A A^\prime}_2 \norm{r^c}_2$. 

Choose $\alpha = \argmin_\alpha \norm{I - \alpha A A^\prime}_2$. 

**Strategy 4**

Note that $\norm{x_{k+1} - x^*}_2 \le \norm{I-\alpha A A^\prime}_2 \norm{x_k - x^*}_2$. 

Choose $\alpha = \argmin_\alpha \norm{I-\alpha A A^\prime}_2 \norm{x_k - x^*}_2$. 

### Conjugate Gradient

#### Orthogonal Search Directions

Let $A \in \R^{d \times d}$ be a symmetric positive definite matrix, $\{x_k\}$ be a sequence where $x_0$ is arbitrary, and

$$x_{k+1} = x_k - \alpha_k s_k.$$

We call $\alpha_k$ the step length, and $s_k$ the search direction.

The question is then: given an orthonormal set of vectors $\{s_k\}$ and an arbitrary $x_0$, how do we choose $\alpha_k$ such that we eventually find $x^*$ with $Ax^* = b$?

From $\{s_k\}$, take all unique vectors: $s_0, s_1, ..., s_{d_1}$ (note: we there are at most $d$ since these are orthonormal vectors from $\R^d$). Since we assumed that $A$ is positive definite, it is invertible. Let $x^* = A^{-1}x$ and take $\alpha_k = \left<x_0 - x^*, s_k\right>$.

This gives us that

\begin{align}
  x_0 - x^* &= \sum_{i=0}^{d-1} \alpha_i s_i \iff \\
  x_0 - \sum_{i=0}^{d-1} \alpha_i s_i &= x^*
\end{align}

But since $x_k - x_{k+1} = \alpha_k s_k$, 

\begin{align}
  x^* &= x_0 - \sum_{i=0}^{d-1} \alpha_i s_i \\
      &= x_0 - \sum_{i=0}^{d-1} (x_i - x_{i+1}) \\ 
      &= x_d.
\end{align}

So, this choice of $\alpha_k$ ensures that we will eventually find the solution. Since $A$ is symmetric and positive definite,

\begin{align}
  \alpha_k &= (x_0 - x^*)^\prime s_k \\
           &= (Ax_0 - Ax^*)^\prime A^{-1} s_k \\
           &= (Ax_0 - b)^\prime A^{-1} s_k \\
           &= \left<Ax_0 - b, s_k\right>_{A^{-1}}.
\end{align}

This shows us that our choice of $\alpha_k$ is actually the inner product of $Ax_0 - b$ and $s_k$ with respect to the matrix $A^{-1}$. But calculating $A^{-1}$ requires a lot of effort. 

Now, what if we use the inner product $\left<\cdot,\cdot\right>_A$ instead? I.e. $\alpha_k = \left<x_0-x^*,s_k\right>_A = (Ax_0 - Ax^*)^\prime s_k = r_0^\prime s_k$. This we can actually calculate. The problem now is that the $s_k$'s are not orthonormal in this new metric. So, we need a way to create a set that is:

#### Conjugation 

```{definition, name = "Conjugated Set"}
A set of vectors $\{s_0, \ldots, s_{d-1}\} \subset \R^d$ are ($A-$)conjugated if they are orthogonal w.r.t. the metric $<\cdot,\cdot>_A$ (i.e. $s_i^\prime A s_j = 0$ for all $i \neq j$).
```

We can use Gram-Schmidt to do this: given a set of linearly independent vectors $\{a_0, ..., a_{d-1}\}$, let $s_0 = \frac{a_0}{\norm{a_0}_A}$ and 

$$
  s_j = \frac{a_j - \sum_{i=0}^{j-1} <a_j, s_i>_A \cdot s_i}{\norm{a_j - \sum_{i=0}^{j-1} <a_j, s_i>_A \cdot s_i}_A}
$$

for all $j > 0$. 

Given a set $\{s_0, ..., s_{d-1}\}$ that is $A-$conjugated and an arbitrary $x_0$, pick 

$$\alpha_k = \frac{<x_0-x^*, s_k>_A}{\norm{s_k}_A} = \frac{r_0^\prime s_k}{\norm{s_k}_A}.$$

```{lemma}
Let $A \in \R^{d\times d}$ be a symmetric, positive definite matrix (i.e. all eigenvalues are positive), $b\in \R^d$ be arbitrary, and $x^* \in \R^d$ such that $Ax^* = b$. Let $\{s_0, ..., s_{d-1}\}$ be an $A-$conjugated and $A-$normalized set, and $x_0 \in \R^d$ be arbitrary. 

Define the sequence $\{x_k\}$ by $x_{k+1} = x_k - \alpha_k s_k$, where $\alpha_k = r_k^\prime s_k$. 
Then the following hold:

1) $\alpha_k = r_0^\prime s_k$, 
2) $0 = r_{k+1}^\prime s_j$ for all $j=0,1,...,k$. 
3) $x_d = x^*$.

```

```{proof}
By definition, $x_k = x_0 - \sum_{i=0}^{k-1} \alpha_i s_i$. This implies that $Ax_k = r_k = r_0 - \sum_{i=0}^{k-1} \alpha_i A s_i$. 

WTS (1): 
  
$$\begin{aligned}
  \alpha_k &= s_k^\prime r_k \\
           &= s_k^\prime r_0 - \sum_{i=0}^{k-1}\alpha_i s_k^\prime A s_i \\
           &= s_k^\prime r_0 - \sum_{i=0}^{k-1}\alpha_i <s_k,s_i>_A \\
           &= s_k^\prime r_0
\end{aligned}$$
  
WTS (2): Let $l < k$. Recall that $A$ is symmetrical, i.e. $A^\prime = A$, and $s_i^\prime A s_l = 0$ for all $i \neq l$. Now, 
  
$$\begin{aligned}
  r_{k+1}^\prime s_l &= \left(r_0 - \sum_{i=0}^k \alpha_i A s_i\right)^\prime s_l \\
                     &= r_0^\prime s_l - \sum_{i=0}^k \alpha_i s_i^\prime A^\prime s_l \\
                     &= \alpha_l - \alpha_l s_l^\prime A s_l = 0.
\end{aligned}$$
  
WTS (3): Suppose $x_d \neq x^*$. Then $r_d = Ax_d - b \neq 0$. But (2) implies that $r_d^\prime s_l = 0$ for all $l < d$. I.e. $r_d$ is linearly independent of $\text{span}\{s_0, ..., s_{d-1}\} \subset \R^d$, so $r_d$ must be $0$, which contradicts the assumption that $x_d \neq x^*$.

```

#### What is the choice of vectors to conjugate? (ref:conjugated_gradients)

Conjugate gradient $A-$conjugates residuals $r_0, ..., r_{d-1}$. 

**Step 0**: given arbitrary $x_0 \in \R^d$, compute $s_0 = \frac{r_0}{\norm{r_0}_A}$. Update the iterate to $x_1 = x_0 - \alpha_0 s_0$, where $\alpha_0 = r_0^\prime s_0$, and update the residual to $r_1 = r_0 - \alpha_0 A s_0$. 

**Step 1**: 

i) $U_{12} = <r_1, s_0>_A = r_1^\prime A s_0 = r_1^\prime \frac{r_0-r_1}{\alpha_0} = -\frac{\norm{r_1}^2}{\alpha_0}$, since $r_0 \perp r_1$.
ii) Unnormalized $A-$conjugate direction: $P_1 = r_1 - U_{12} \cdot s_0$.
iii) Normalize and compute search direction: $U_{22} = \norm{P_1}_A$ and $s_1 = \frac{P_1}{U_{22}}$. 

_Update_: $x_2 = x_1 - \alpha_1 s_1$ and $r_2 = r_1 - \alpha_1 A s_1$, where $\alpha_1 = r_1^\prime s_1 = \left(r_1^\prime r_1 - U_{12} r_1^\prime s_0\right)/U_{22} = \frac{\norm{r_1}_2^2}{U_{22}}$ (since $r_1^\prime s_0 = 0$). 

Check that lemma still holds: 

i) step length: $\alpha_1 = r_1^\prime s_1 = (r_0 - \alpha_0 A s_0)^\prime s_1 = r_0^\prime s_1$
ii) orthogonality: $r_2^\prime s_j = r_0 - \alpha_0 A s_0 - \alpha_1 A s_1)^\prime s_j = r_0^\prime s_j - \alpha_j = 0$.

A few key observations: 

i) $r_0 \in \text{span}\{s_0\}, r_1 \in \text{span}\{s_0,s_1\}$. 
ii) since $r_2 \perp s_0, s_1$, $r_2^\prime r_j = 0$ for $j=0,1$. 

In general, let's say we're at step $L$. This means we have already calculated $s_0, ..., s_{L-1}$, $r_0,...,r_L$, and $x_0,...,x_L$. To get the next iterate, we would do the following:

A) Gram-Schmidt:
    1. Compute the inner products for $x_L$ with $s_j$ for all $j < L$. Recall that $r_{j+1} = r_j - \alpha_j r_L^\prime A s_j$. For $j < L-1$: $<r_L, s_j>_A = r_L^\prime A s_j = r_L^\prime \left(\frac{r_{j+1} - r_j}{-\alpha_j}\right) = 0$, since $r_L \perp s_j$ for all $j < L-1$, and $r_j$ is simply a linear combination of these. <\br>
       For $j = L-1$: $<r_L, s_{L-1}>_A = r_A^\prime \left(\frac{r_L - r_{L-1}}{-\alpha_{L-1}}\right) = \frac{\norm{r_L}_2^2}{-\alpha_{L-1}}$.
    2. Find unnormalized search direction: \newline
       $P_L = r_L - \sum_{j=0}^{L-1} <r_L, s_j>_A s_j = r_L + \frac{\norm{r_L}_2^2}{\alpha_{L-1}}s_{L-1}$
    3. Calculate normalization constant: $\norm{P_L}_A$
    4. Calculate final normalization direction: $s_L = \frac{P_L}{\norm{P_L}_A}$.
B) Update iterates:
    1. $\alpha_L = <s_L, r_L> = \frac{\norm{r_L}_2^2}{\norm{P_L}_A}$.
    2. $x_{L+1} = x_L - \alpha_L s_L$.
    3. $r_{L+1} = r_L - \alpha_L A s_L$.

When working with exact arithmetic, CG is guaranteed to converge in a finite number of steps. However, when implementing in algorithms, there's no such guarentee. It will converge in the limit, and the convergence rate is of the order $\frac{\sqrt{k} - 1}{\sqrt{k} + 1}$, where $k$ is the condition number. If $k$ is very large, the convergence happens very slowly. This is why there are a lot of work being done in socalled "precondition methods", that is methods that aim at transforming the matrix $A$ such that the condition number is smaller, but features are not lost. 

So far, we have talked abouth iterative methods without much motivation or justification. However, as we will see later, iterative methods are very useful when dealing with non-linear systems of equations.

## Nonlinear Systems of Equations

_Outline_: 

I. Review of Jacobians </br>
II. Motivating example: clustered data </br>
III. Non-linear systems of equations </br>
IV. Picard's method </br>
V. Newton's method </br>
VI. Inexact Newton's Method </br>
VII. Linear Search </br>
VIII. Semi-smooth Newton's Method </br>

### Review of Jacobians

```{definition, "Gradient"}
Let $f: \R^m \to \R$. The gradient of $f$ at $x \in \R^m$ is a vector $g$ (if it exists) such that 

$$
  \lim_{h \to 0} \frac{\left| f(x+h) - f(x) - <g,h>\right |}{\norm{h}} = 0.
$$

```

```{example, label = "gradient-example"}
Let $f(z) = z_1 ... z_m$. Guess that the gradient is $g$ with coordinate vectors $g_1(x) = x_2...x_m; ...; g_k(x) = x_1,...,x_{k-1}, x_{k+1}, ..., x_m; ...; g_m(x) = x_1,...,x_{m-1}$. Check that $g$ is the gradient:
  
$$
  \frac{\left|(x_1+h_1)\cdots(x_m+h_m) - x_1\cdots x_m - \sum_{k=1}^m h_k \prod_{i \neq k} x_i \right|}{\sqrt{\sum_{k=1}^m h_k^2}} = \frac{\left| \sum_{k=1}^m \sum_{l\neq k} O(h_k h_l) \right |}{\sqrt{\sum_{k=1}^m h_k^2}} \to 0.
$$
  
```

```{definition, "Jacobian"}
Let $f: \R^m \to \R^n$. The Jacobian at a point $x$ in $\R^m$ (if it exists) is a function satisfying 

$$
  \lim_{h\to 0} \frac{\norm{f(x+h) - f(x) - Jh}}{\norm{h}} = 0.
$$
  
Note that the norm in the numerator is a norm in $\R^n$ and the norm in the denominator is a norm in $\R^m$. 
  
```

```{example, label = "jacobian-example"}
Let $f: \R^m \to \R^{m-1}$ be given by the coordinate functions $f_k(z) = z_k z_{k-1}$. Guess for the Jacobian:
  
$$
  J_{ij} = \left\{ \begin{array}{rl} 0, & j\neq 1, j \neq i+1 \\ x_{i+1}, & j = 1, \\ x_i, & j = i+1 \end{array} \right.
$$
  
```

### Motivating Problem

Consider a scenario where we enroll 100 patients for a study. Each patient will undergo two different treatments for a disease. The treatment is given at visits every two weeks for a one year period. At the first visit, we record which treatment is given, gender $\{0,1\}$, and concentration of the given treatment in the patients blood. For every follow up visit, we record the treatment status $\{0,1,2,3\}$. 

We would like to model the treatment status based on the other mentioned variables. To do so, we assume that the patients are independent, but the disease status is correlated in time (status at closer time points are more likely to be similar). 

To model this data, we let $Y_i \in \{0,1,2,3\}^{26}$ denote the disease statuses collected at the 26 visits for patient $i$, and $X_{ij} \in \{0,1\} \times \{0,1\} \times (0,1)$ is the covariate matrix for the $i$'th patient at time point $j$. For a vector of coefficients $\beta \in \R^p$, a correlation value $\rho \in [0,1]$, and a function $\mu: \R^p \times (\{0,1\} \times \{0,1\} \times (0,1)) \to \{0,1,2,3\}$, we define a variance function 

$$
  V_{lj}(\rho, \beta, X_{i\cdot}) = \rho^{\vert l-j\vert}(\mu(\beta, X_{il}) + 1)(\mu(\beta, X_{ij}) + 1).
$$

Let $M(\beta, X_{i\cdot}) = \begin{pmatrix} \mu(\beta, X_{i1}) & \cdots & \mu(\beta, X_{i26}) \end{pmatrix}^\prime$. Now, an estimator of $\beta$ can be found by solving the equation 

$$
  0 = \sum_{i=1}^N J(\beta, X_{i\cdot})^\prime V^{-1}(\rho, \beta, X_{i\cdot})(Y_i - M(\beta, X_{i\cdot})).
$$

### Non-linear Equations

#### Problem Formulation

The problems we will be looking at here can be formulated as $0 = F(x)$, where $F:\R^m \to \R^n$, or (if the righthand side is "nice enough") $x = G(x)$, where $G: \R^m \to \R^m$. 

#### Uniqueness

In order to be able to discuss uniqueness of solutions to non-linear equations, we need the implicit function theorem.

```{theorem, name = "Linear Case of the Implicit Function Theorme"}

Let $M \in \R^{n\times m}$, where $m>n$ and $\text{rank}(H) = n$. Without loss of generality, let $M = \begin{bmatrix} A & B \end{bmatrix}$, where $A \in \R^{n\times n}$ is invertible. 

Then, for all $x \in \R^{m-n}$, $z = \begin{bmatrix} -A^{-1}Bx & x \end{bmatrix}^\prime$ satisfies $Mz = 0$.

```

```{theorem, name = "Implicit Function Theorem"}
Let $F:\R^m \to \R^n$ be continuously differentiable. Then $F$ has a Jacobian, $J:\R^m \to \R^{n\times m}$. 

Suppose $z^*$ satisfies $F(z^*) = 0$. Without loss of generality, suppose $J(z^*) = \begin{bmatrix} J_1(z^*) & J_2(z^*) \end{bmatrix}$, where $J_1(z^*) \in \R^{n\times n}$ is invertible. Then there exists an open neighborhood $U \subseteq \R^{n\times n}$, and a continuous function $g: U \to \R^n$ such that for all $x \in U$, $z= \begin{bmatrix} g(x) & x \end{bmatrix}^\prime$ satisfies that $F(z) = 0$. 
```